window.WORD_SNAP_STAGE_LISTS = window.WORD_SNAP_STAGE_LISTS || {};
window.WORD_SNAP_STAGE_LISTS["初一课内词汇"] = {"grade":"初一课内词汇","goals":["初一课内词汇"],"source":"初一课内词汇","words":[
    {"en":"greet","zh":"和（某人）打招呼（或问好）","pos":"","notes":"","frequency":0},
    {"en":"introduce","zh":"介绍","pos":"","notes":"","frequency":0},
    {"en":"each other","zh":"互相","pos":"","notes":"","frequency":0},
    {"en":"go by","zh":"叫作，被称为","pos":"","notes":"","frequency":0},
    {"en":"glad","zh":"高兴","pos":"","notes":"","frequency":0},
    {"en":"same","zh":"同一的，相同的","pos":"","notes":"","frequency":0},
    {"en":"hobby","zh":"业余爱好","pos":"","notes":"","frequency":0},
    {"en":"grade","zh":"年级，等级","pos":"","notes":"","frequency":0},
    {"en":"classmate","zh":"同班同学","pos":"","notes":"","frequency":0},
    {"en":"friendly","zh":"友好的","pos":"","notes":"","frequency":0},
    {"en":"full","zh":"（有）大量的，满的","pos":"","notes":"","frequency":0},
    {"en":"be full of","zh":"满是……的","pos":"","notes":"","frequency":0},
    {"en":"energy","zh":"精力，活力","pos":"","notes":"","frequency":0},
    {"en":"be good at","zh":"擅长……","pos":"","notes":"","frequency":0},
    {"en":"slim","zh":"苗条的","pos":"","notes":"","frequency":0},
    {"en":"polite","zh":"有礼貌的","pos":"","notes":"","frequency":0},
    {"en":"smart","zh":"聪明的，智能的","pos":"","notes":"","frequency":0},
    {"en":"ready","zh":"愿意迅速做某事，准备好","pos":"","notes":"","frequency":0},
    {"en":"be ready to do sth","zh":"愿意（或准备好）做某事","pos":"","notes":"","frequency":0},
    {"en":"other","zh":"另外，其他","pos":"","notes":"","frequency":0},
    {"en":"interested","zh":"感兴趣的","pos":"","notes":"","frequency":0},
    {"en":"be interested in","zh":"对……感兴趣","pos":"","notes":"","frequency":0},
    {"en":"looks","zh":"相貌，容貌","pos":"","notes":"","frequency":0},
    {"en":"character","zh":"性格","pos":"","notes":"","frequency":0},
    {"en":"both","zh":"两个都","pos":"","notes":"","frequency":0},
    {"en":"enjoy","zh":"享受……的乐趣，欣赏，喜爱","pos":"","notes":"","frequency":0},
    {"en":"pretty","zh":"漂亮的，标致的","pos":"","notes":"","frequency":0},
    {"en":"shy","zh":"腼腆的","pos":"","notes":"","frequency":0},
    {"en":"only","zh":"只有，仅","pos":"","notes":"","frequency":0},
    {"en":"stay","zh":"保持，继续是，停留，逗留","pos":"","notes":"","frequency":0},
    {"en":"match","zh":"比赛","pos":"","notes":"","frequency":0},
    {"en":"luck","zh":"幸运，好运","pos":"","notes":"","frequency":0},
    {"en":"good luck","zh":"祝成功，祝好运","pos":"","notes":"","frequency":0},
    {"en":"chess","zh":"国际象棋","pos":"","notes":"","frequency":0},
    {"en":"Chinese chess","zh":"中国象棋","pos":"","notes":"","frequency":0},
    {"en":"problem","zh":"数学题，难题，困难","pos":"","notes":"","frequency":0},
    {"en":"weekend","zh":"周末","pos":"","notes":"","frequency":0},
    {"en":"at the weekend","zh":"在周末","pos":"","notes":"","frequency":0},
    {"en":"fun","zh":"有趣的，使人快乐的，开心，乐趣，好玩的事","pos":"","notes":"","frequency":0},
    {"en":"make friends with","zh":"与……交朋友","pos":"","notes":"","frequency":0},
    {"en":"jog","zh":"慢跑，慢步长跑","pos":"","notes":"","frequency":0},
    {"en":"paint","zh":"用颜料画，在……上刷油漆，绘画颜料，油漆","pos":"","notes":"","frequency":0},
    {"en":"paper-cutting","zh":"剪纸","pos":"","notes":"","frequency":0},
    {"en":"all kinds of","zh":"各种各样的","pos":"","notes":"","frequency":0},
    {"en":"fit","zh":"健康的","pos":"","notes":"","frequency":0},
    {"en":"around","zh":"围绕，环绕，到处，向各处","pos":"","notes":"","frequency":0},
    {"en":"change","zh":"使不同，改变，变化","pos":"","notes":"","frequency":0},
    {"en":"life","zh":"个人生活，生命","pos":"","notes":"","frequency":0},
    {"en":"museum","zh":"博物馆","pos":"","notes":"","frequency":0},
    {"en":"thing","zh":"东西","pos":"","notes":"","frequency":0},
    {"en":"apart","zh":"分开","pos":"","notes":"","frequency":0},
    {"en":"take apart","zh":"拆卸，拆开","pos":"","notes":"","frequency":0},
    {"en":"fix","zh":"修理，安装","pos":"","notes":"","frequency":0},
    {"en":"endless","zh":"无穷无尽的，不计其数的","pos":"","notes":"","frequency":0},
    {"en":"scientist","zh":"科学家","pos":"","notes":"","frequency":0},
    {"en":"dream","zh":"梦想，梦","pos":"","notes":"","frequency":0},
    {"en":"true","zh":"真正的，实质的，确实的","pos":"","notes":"","frequency":0},
    {"en":"come true","zh":"实现，成为现实","pos":"","notes":"","frequency":0},
    {"en":"club","zh":"社团，俱乐部","pos":"","notes":"","frequency":0},
    {"en":"member","zh":"成员","pos":"","notes":"","frequency":0},
    {"en":"geography","zh":"地理（学）","pos":"","notes":"","frequency":0},
    {"en":"p.m.","zh":"下午","pos":"","notes":"","frequency":0},
    {"en":"volleyball","zh":"排球运动","pos":"","notes":"","frequency":0},
    {"en":"each","zh":"每个，各自","pos":"","notes":"","frequency":0},
    {"en":"once","zh":"一次","pos":"","notes":"","frequency":0},
    {"en":"join","zh":"加入，与……一道去","pos":"","notes":"","frequency":0},
    {"en":"meeting","zh":"集合，会面，会议","pos":"","notes":"","frequency":0},
    {"en":"sound","zh":"听起来好像","pos":"","notes":"","frequency":0},
    {"en":"plan","zh":"打算，计划","pos":"","notes":"","frequency":0},
    {"en":"questionnaire","zh":"调查表，问卷","pos":"","notes":"","frequency":0},
    {"en":"role","zh":"角色","pos":"","notes":"","frequency":0},
    {"en":"model","zh":"模范，典型，模特儿","pos":"","notes":"","frequency":0},
    {"en":"role model","zh":"楷模，行为榜样","pos":"","notes":"","frequency":0},
    {"en":"design","zh":"设计","pos":"","notes":"","frequency":0},
    {"en":"skill","zh":"技能，技艺","pos":"","notes":"","frequency":0},
    {"en":"painting","zh":"画作","pos":"","notes":"","frequency":0},
    {"en":"artist","zh":"艺术家，画家","pos":"","notes":"","frequency":0},
    {"en":"master","zh":"能手，擅长……者，大师，师父","pos":"","notes":"","frequency":0},
    {"en":"work","zh":"作品，著作","pos":"","notes":"","frequency":0},
    {"en":"become","zh":"成为，开始变得","pos":"","notes":"","frequency":0},
    {"en":"designer","zh":"设计师","pos":"","notes":"","frequency":0},
    {"en":"would","zh":"想（表示愿意、喜欢、不愿意等）","pos":"","notes":"","frequency":0},
    {"en":"would like","zh":"愿意，想要","pos":"","notes":"","frequency":0},
    {"en":"future","zh":"未来","pos":"","notes":"","frequency":0},
    {"en":"in the future","zh":"在未来","pos":"","notes":"","frequency":0},
    {"en":"hope","zh":"希望","pos":"","notes":"","frequency":0},
    {"en":"gym","zh":"体育馆","pos":"","notes":"","frequency":0},
    {"en":"building","zh":"楼房，建筑物","pos":"","notes":"","frequency":0},
    {"en":"field","zh":"运动场","pos":"","notes":"","frequency":0},
    {"en":"sports field","zh":"体育场","pos":"","notes":"","frequency":0},
    {"en":"dining","zh":"吃饭","pos":"","notes":"","frequency":0},
    {"en":"hall","zh":"大厅，礼堂","pos":"","notes":"","frequency":0},
    {"en":"dining hall","zh":"食堂，餐厅","pos":"","notes":"","frequency":0},
    {"en":"lab","zh":"实验室","pos":"","notes":"","frequency":0},
    {"en":"part","zh":"部分","pos":"","notes":"","frequency":0},
    {"en":"modern","zh":"现代化的，先进的，现代的","pos":"","notes":"","frequency":0},
    {"en":"as well","zh":"也","pos":"","notes":"","frequency":0},
    {"en":"bright","zh":"明亮的","pos":"","notes":"","frequency":0},
    {"en":"everyone","zh":"所有人，每人，人人","pos":"","notes":"","frequency":0},
    {"en":"perfect","zh":"完美的","pos":"","notes":"","frequency":0},
    {"en":"spend","zh":"度过，花（时间），花（钱）","pos":"","notes":"","frequency":0},
    {"en":"chat","zh":"闲聊","pos":"","notes":"","frequency":0},
    {"en":"exciting","zh":"令人激动的","pos":"","notes":"","frequency":0},
    {"en":"take place","zh":"进行，发生","pos":"","notes":"","frequency":0},
    {"en":"noticeboard","zh":"布告板，告示牌","pos":"","notes":"","frequency":0},
    {"en":"gate","zh":"大门","pos":"","notes":"","frequency":0},
    {"en":"news","zh":"新闻，消息","pos":"","notes":"","frequency":0},
    {"en":"board","zh":"布告牌，木板","pos":"","notes":"","frequency":0},
    {"en":"like","zh":"例如，像","pos":"","notes":"","frequency":0},
    {"en":"more","zh":"更多的，更大的，更，更多","pos":"","notes":"","frequency":0},
    {"en":"trust","zh":"相信","pos":"","notes":"","frequency":0},
    {"en":"really","zh":"很，十分，真正地","pos":"","notes":"","frequency":0},
    {"en":"soon","zh":"很快，马上","pos":"","notes":"","frequency":0},
    {"en":"teach","zh":"教（课程），讲授","pos":"","notes":"","frequency":0},
    {"en":"team","zh":"队，组","pos":"","notes":"","frequency":0},
    {"en":"form teacher","zh":"班主任","pos":"","notes":"","frequency":0},
    {"en":"show","zh":"演出，展览，节目，音乐会","pos":"","notes":"","frequency":0},
    {"en":"grey","zh":"灰色的，灰色","pos":"","notes":"","frequency":0},
    {"en":"different","zh":"不同的","pos":"","notes":"","frequency":0},
    {"en":"thousand","zh":"一千","pos":"","notes":"","frequency":0},
    {"en":"fact","zh":"事实","pos":"","notes":"","frequency":0},
    {"en":"in fact","zh":"确切地说，事实上","pos":"","notes":"","frequency":0},
    {"en":"borrow","zh":"借","pos":"","notes":"","frequency":0},
    {"en":"newspaper","zh":"报纸","pos":"","notes":"","frequency":0},
    {"en":"magazine","zh":"杂志","pos":"","notes":"","frequency":0},
    {"en":"else","zh":"其他的，别的","pos":"","notes":"","frequency":0},
    {"en":"care","zh":"关心，照顾，小心","pos":"","notes":"","frequency":0},
    {"en":"care about","zh":"关心","pos":"","notes":"","frequency":0},
    {"en":"event","zh":"公开活动，发生的事情","pos":"","notes":"","frequency":0},
    {"en":"together","zh":"在一起，共同","pos":"","notes":"","frequency":0},
    {"en":"quite","zh":"相当，非常","pos":"","notes":"","frequency":0},
    {"en":"large","zh":"大的","pos":"","notes":"","frequency":0},
    {"en":"special","zh":"特殊的，特别的","pos":"","notes":"","frequency":0},
    {"en":"a.m.","zh":"上午","pos":"","notes":"","frequency":0},
    {"en":"get up","zh":"起床","pos":"","notes":"","frequency":0},
    {"en":"activity","zh":"活动","pos":"","notes":"","frequency":0},
    {"en":"housework","zh":"家务劳动，家务事","pos":"","notes":"","frequency":0},
    {"en":"homework","zh":"家庭作业","pos":"","notes":"","frequency":0},
    {"en":"weekday","zh":"周工作日","pos":"","notes":"","frequency":0},
    {"en":"on weekdays","zh":"在工作日","pos":"","notes":"","frequency":0},
    {"en":"usually","zh":"通常地","pos":"","notes":"","frequency":0},
    {"en":"a little","zh":"一点，少量，少量的，一些","pos":"","notes":"","frequency":0},
    {"en":"myself","zh":"我自己，亲自","pos":"","notes":"","frequency":0},
    {"en":"enjoy oneself","zh":"玩得痛快，得到乐趣","pos":"","notes":"","frequency":0},
    {"en":"first","zh":"第一，首先","pos":"","notes":"","frequency":0},
    {"en":"term","zh":"学期，期","pos":"","notes":"","frequency":0},
    {"en":"start","zh":"开始，着手，开头，开端","pos":"","notes":"","frequency":0},
    {"en":"writer","zh":"作家","pos":"","notes":"","frequency":0},
    {"en":"language","zh":"语言","pos":"","notes":"","frequency":0},
    {"en":"amazing","zh":"令人大为惊奇的","pos":"","notes":"","frequency":0},
    {"en":"biology","zh":"生物学","pos":"","notes":"","frequency":0},
    {"en":"living","zh":"活着的，活的","pos":"","notes":"","frequency":0},
    {"en":"nature","zh":"大自然，天性","pos":"","notes":"","frequency":0},
    {"en":"practise","zh":"训练，练习","pos":"","notes":"","frequency":0},
    {"en":"field","zh":"田，地，领域","pos":"","notes":"","frequency":0},
    {"en":"trip","zh":"旅行","pos":"","notes":"","frequency":0},
    {"en":"field trip","zh":"野外考察，实地考察","pos":"","notes":"","frequency":0},
    {"en":"leave","zh":"离开，使保留","pos":"","notes":"","frequency":0},
    {"en":"leave for","zh":"动身去，到……地方去","pos":"","notes":"","frequency":0},
    {"en":"pick","zh":"采，摘，挑选","pos":"","notes":"","frequency":0},
    {"en":"of course","zh":"当然","pos":"","notes":"","frequency":0},
    {"en":"seldom","zh":"很少","pos":"","notes":"","frequency":0},
    {"en":"tennis","zh":"网球运动","pos":"","notes":"","frequency":0},
    {"en":"roller skate","zh":"滑旱冰，溜旱冰","pos":"","notes":"","frequency":0},
    {"en":"grow","zh":"（使）生长，发育","pos":"","notes":"","frequency":0},
    {"en":"tour","zh":"参观，旅行","pos":"","notes":"","frequency":0},
    {"en":"website","zh":"网站","pos":"","notes":"","frequency":0},
    {"en":"video","zh":"视频","pos":"","notes":"","frequency":0},
    {"en":"outside","zh":"在（向）外面，在（向）……外面","pos":"","notes":"","frequency":0},
    {"en":"peace","zh":"平静，和平","pos":"","notes":"","frequency":0},
    {"en":"quiet","zh":"宁静，平静","pos":"","notes":"","frequency":0},
    {"en":"teamwork","zh":"团队合作","pos":"","notes":"","frequency":0},
    {"en":"better","zh":"更好的","pos":"","notes":"","frequency":0},
    {"en":"tiring","zh":"累人的","pos":"","notes":"","frequency":0},
    {"en":"duty","zh":"职责，任务，责任，义务","pos":"","notes":"","frequency":0},
    {"en":"area","zh":"区域，面积，领域","pos":"","notes":"","frequency":0},
    {"en":"take part in","zh":"参加","pos":"","notes":"","frequency":0},
    {"en":"through","zh":"以，凭借，通过，穿过","pos":"","notes":"","frequency":0},
    {"en":"group","zh":"组，群，批","pos":"","notes":"","frequency":0},
    {"en":"turn","zh":"（依次轮到的）机会","pos":"","notes":"","frequency":0},
    {"en":"take turns","zh":"轮流","pos":"","notes":"","frequency":0},
    {"en":"empty","zh":"倒空，腾空，空的","pos":"","notes":"","frequency":0},
    {"en":"bin","zh":"垃圾桶","pos":"","notes":"","frequency":0},
    {"en":"take care of","zh":"照顾，照料","pos":"","notes":"","frequency":0},
    {"en":"something","zh":"某事，某物","pos":"","notes":"","frequency":0},
    {"en":"lifestyle","zh":"生活方式","pos":"","notes":"","frequency":0},
    {"en":"cucumber","zh":"黄瓜","pos":"","notes":"","frequency":0},
    {"en":"lemon","zh":"柠檬","pos":"","notes":"","frequency":0},
    {"en":"watermelon","zh":"西瓜","pos":"","notes":"","frequency":0},
    {"en":"pepper","zh":"甜椒，胡椒粉","pos":"","notes":"","frequency":0},
    {"en":"chocolate","zh":"巧克力","pos":"","notes":"","frequency":0},
    {"en":"beef","zh":"牛肉","pos":"","notes":"","frequency":0},
    {"en":"carrot","zh":"胡萝卜","pos":"","notes":"","frequency":0},
    {"en":"pork","zh":"猪肉","pos":"","notes":"","frequency":0},
    {"en":"sweet","zh":"糖果，甜食，甜的，可爱的","pos":"","notes":"","frequency":0},
    {"en":"snack","zh":"点心，小吃","pos":"","notes":"","frequency":0},
    {"en":"health","zh":"健康","pos":"","notes":"","frequency":0},
    {"en":"delicious","zh":"美味的","pos":"","notes":"","frequency":0},
    {"en":"important","zh":"重要的","pos":"","notes":"","frequency":0},
    {"en":"diet","zh":"日常饮食","pos":"","notes":"","frequency":0},
    {"en":"without","zh":"没有","pos":"","notes":"","frequency":0},
    {"en":"pancake","zh":"烙饼，薄饼","pos":"","notes":"","frequency":0},
    {"en":"tofu","zh":"豆腐","pos":"","notes":"","frequency":0},
    {"en":"sugar","zh":"食糖","pos":"","notes":"","frequency":0},
    {"en":"tooth","zh":"牙，齿","pos":"","notes":"","frequency":0},
    {"en":"homebody","zh":"喜欢待在家里的人","pos":"","notes":"","frequency":0},
    {"en":"mutton","zh":"羊肉","pos":"","notes":"","frequency":0},
    {"en":"have a sweet tooth","zh":"爱吃甜食","pos":"","notes":"","frequency":0},
    {"en":"stay up","zh":"熬夜","pos":"","notes":"","frequency":0},
    {"en":"unhealthy","zh":"不健康的","pos":"","notes":"","frequency":0},
    {"en":"need","zh":"需要，需要的事物，需要","pos":"","notes":"","frequency":0},
    {"en":"enough","zh":"足够（的），足够地，相当","pos":"","notes":"","frequency":0},
    {"en":"less","zh":"较少的，更少的，少，较少","pos":"","notes":"","frequency":0},
    {"en":"cheese","zh":"奶酪","pos":"","notes":"","frequency":0},
    {"en":"piece","zh":"块，片，一篇（首、幅等）","pos":"","notes":"","frequency":0},
    {"en":"bowl","zh":"一碗（的量），碗","pos":"","notes":"","frequency":0},
    {"en":"salt","zh":"盐","pos":"","notes":"","frequency":0},
    {"en":"packet","zh":"小袋，小包装纸袋","pos":"","notes":"","frequency":0},
    {"en":"kilo","zh":"千克，公斤","pos":"","notes":"","frequency":0},
    {"en":"carton","zh":"硬纸盒，塑料盒","pos":"","notes":"","frequency":0},
    {"en":"bottle","zh":"一瓶（的量），瓶子","pos":"","notes":"","frequency":0},
    {"en":"maybe","zh":"也许，大概","pos":"","notes":"","frequency":0},
    {"en":"than","zh":"比","pos":"","notes":"","frequency":0},
    {"en":"almost","zh":"几乎","pos":"","notes":"","frequency":0},
    {"en":"chip","zh":"炸薯条，炸薯片","pos":"","notes":"","frequency":0},
    {"en":"smartphone","zh":"智能手机","pos":"","notes":"","frequency":0},
    {"en":"tablet","zh":"平板电脑","pos":"","notes":"","frequency":0},
    {"en":"score","zh":"分数，成绩，比分","pos":"","notes":"","frequency":0},
    {"en":"point","zh":"得分，要点，观点，地点","pos":"","notes":"","frequency":0},
    {"en":"meal","zh":"一餐所吃的食物，一顿饭","pos":"","notes":"","frequency":0},
    {"en":"porridge","zh":"粥，麦片粥","pos":"","notes":"","frequency":0},
    {"en":"whole","zh":"全部的，整个的，全部，整个","pos":"","notes":"","frequency":0},
    {"en":"miss","zh":"错过","pos":"","notes":"","frequency":0},
    {"en":"rest","zh":"休息时间","pos":"","notes":"","frequency":0},
    {"en":"pie","zh":"馅饼","pos":"","notes":"","frequency":0},
    {"en":"yogurt","zh":"酸奶","pos":"","notes":"","frequency":0},
    {"en":"most","zh":"大多数，几乎所有，最大，最多","pos":"","notes":"","frequency":0},
    {"en":"style","zh":"样式，方式，作风","pos":"","notes":"","frequency":0},
    {"en":"blouse","zh":"女式衬衫","pos":"","notes":"","frequency":0},
    {"en":"jacket","zh":"夹克衫","pos":"","notes":"","frequency":0},
    {"en":"jeans","zh":"牛仔裤","pos":"","notes":"","frequency":0},
    {"en":"scarf","zh":"围巾","pos":"","notes":"","frequency":0},
    {"en":"tie","zh":"领带","pos":"","notes":"","frequency":0},
    {"en":"T-shirt  T","zh":"恤衫","pos":"","notes":"","frequency":0},
    {"en":"calm","zh":"镇静的，沉着的","pos":"","notes":"","frequency":0},
    {"en":"fashion","zh":"时装业，流行","pos":"","notes":"","frequency":0},
    {"en":"choose","zh":"选择","pos":"","notes":"","frequency":0},
    {"en":"could","zh":"能，可以","pos":"","notes":"","frequency":0},
    {"en":"advice","zh":"建议","pos":"","notes":"","frequency":0},
    {"en":"depend","zh":"取决于","pos":"","notes":"","frequency":0},
    {"en":"depend on","zh":"取决于，依靠","pos":"","notes":"","frequency":0},
    {"en":"skin","zh":"皮肤","pos":"","notes":"","frequency":0},
    {"en":"such as","zh":"例如，诸如……之类","pos":"","notes":"","frequency":0},
    {"en":"purple","zh":"紫色，紫色的","pos":"","notes":"","frequency":0},
    {"en":"similar","zh":"相似的","pos":"","notes":"","frequency":0},
    {"en":"example","zh":"例子","pos":"","notes":"","frequency":0},
    {"en":"for example","zh":"例如","pos":"","notes":"","frequency":0},
    {"en":"dark","zh":"深色的，黑暗的，黑暗，暗处","pos":"","notes":"","frequency":0},
    {"en":"mix","zh":"混合","pos":"","notes":"","frequency":0},
    {"en":"stand out","zh":"突出，显眼","pos":"","notes":"","frequency":0},
    {"en":"match","zh":"般配，相配","pos":"","notes":"","frequency":0},
    {"en":"suitable","zh":"合适的，适宜的","pos":"","notes":"","frequency":0},
    {"en":"formal","zh":"适合正式场合的，庄重的，正式的","pos":"","notes":"","frequency":0},
    {"en":"suit","zh":"套装，西服","pos":"","notes":"","frequency":0},
    {"en":"casual","zh":"非正式的，随便的","pos":"","notes":"","frequency":0},
    {"en":"comfortable","zh":"舒适的","pos":"","notes":"","frequency":0},
    {"en":"primary","zh":"初等教育的，小学教育的","pos":"","notes":"","frequency":0},
    {"en":"smart","zh":"衣冠楚楚的，衣着讲究的","pos":"","notes":"","frequency":0},
    {"en":"date","zh":"日期","pos":"","notes":"","frequency":0},
    {"en":"traditional","zh":"传统的","pos":"","notes":"","frequency":0},
    {"en":"popular","zh":"广受欢迎的，流行的","pos":"","notes":"","frequency":0},
    {"en":"type","zh":"类型，种类","pos":"","notes":"","frequency":0},
    {"en":"festival","zh":"节日，节","pos":"","notes":"","frequency":0},
    {"en":"wedding","zh":"婚礼","pos":"","notes":"","frequency":0},
    {"en":"just","zh":"仅仅，只不过，正好","pos":"","notes":"","frequency":0},
    {"en":"culture","zh":"文化","pos":"","notes":"","frequency":0},
    {"en":"country","zh":"国家","pos":"","notes":"","frequency":0},
    {"en":"history","zh":"历史","pos":"","notes":"","frequency":0},
    {"en":"loose","zh":"宽松的","pos":"","notes":"","frequency":0},
    {"en":"belt","zh":"腰带，皮带","pos":"","notes":"","frequency":0},
    {"en":"close-fitting","zh":"紧身的","pos":"","notes":"","frequency":0},
    {"en":"be made of","zh":"由……制成","pos":"","notes":"","frequency":0},
    {"en":"silk","zh":"丝绸","pos":"","notes":"","frequency":0},
    {"en":"feel","zh":"摸起来","pos":"","notes":"","frequency":0},
    {"en":"smooth","zh":"光滑的","pos":"","notes":"","frequency":0},
    {"en":"soft","zh":"软的，柔软的","pos":"","notes":"","frequency":0},
    {"en":"cotton","zh":"棉织物，棉布，棉花","pos":"","notes":"","frequency":0},
    {"en":"agree","zh":"同意","pos":"","notes":"","frequency":0},
    {"en":"feature","zh":"特点，特色","pos":"","notes":"","frequency":0},
    {"en":"material","zh":"布料，材料，原料","pos":"","notes":"","frequency":0},
    {"en":"leather","zh":"皮革","pos":"","notes":"","frequency":0},
    {"en":"size","zh":"尺码，大小","pos":"","notes":"","frequency":0}
]};
