window.WORD_SNAP_STAGE_LISTS = window.WORD_SNAP_STAGE_LISTS || {};
window.WORD_SNAP_STAGE_LISTS["初二课内词汇"] = {"grade":"初二课内词汇","goals":["初二课内词汇"],"source":"初二课内词汇","words":[
    {"en":"friendship","zh":"友谊","pos":"","notes":"","frequency":0},
    {"en":"honest","zh":"诚实的,正直的","pos":"","notes":"","frequency":0},
    {"en":"cheerful","zh":"快乐的,乐观的","pos":"","notes":"","frequency":0},
    {"en":"humorous","zh":"幽默的","pos":"","notes":"","frequency":0},
    {"en":"caring","zh":"关心他人的,体贴人的","pos":"","notes":"","frequency":0},
    {"en":"truth","zh":"事实","pos":"","notes":"","frequency":0},
    {"en":"joke","zh":"笑话,玩笑","pos":"","notes":"","frequency":0},
    {"en":"laugh","zh":"笑,发笑","pos":"","notes":"","frequency":0},
    {"en":"teenager","zh":"青少年","pos":"","notes":"","frequency":0},
    {"en":"unhappy","zh":"不开心的","pos":"","notes":"","frequency":0},
    {"en":"lie","zh":"撒谎","pos":"","notes":"","frequency":0},
    {"en":"person","zh":"人,个人","pos":"","notes":"","frequency":0},
    {"en":"thought","zh":"想法,主意","pos":"","notes":"","frequency":0},
    {"en":"ponytail","zh":"马尾辫","pos":"","notes":"","frequency":0},
    {"en":"seat","zh":"座位","pos":"","notes":"","frequency":0},
    {"en":"schoolwork","zh":"学校作业","pos":"","notes":"","frequency":0},
    {"en":"trustworthy","zh":"值得信赖的","pos":"","notes":"","frequency":0},
    {"en":"carefully","zh":"仔细地,小心地","pos":"","notes":"","frequency":0},
    {"en":"understand","zh":"理解","pos":"","notes":"","frequency":0},
    {"en":"bit","zh":"少量","pos":"","notes":"","frequency":0},
    {"en":"a little bit","zh":"有点儿","pos":"","notes":"","frequency":0},
    {"en":"funny","zh":"好笑的","pos":"","notes":"","frequency":0},
    {"en":"sense","zh":"理解力,感觉","pos":"","notes":"","frequency":0},
    {"en":"humour ( humor)","zh":"幽默","pos":"","notes":"","frequency":0},
    {"en":"sense of humour","zh":"幽默感","pos":"","notes":"","frequency":0},
    {"en":"bored","zh":"厌倦的,烦闷的","pos":"","notes":"","frequency":0},
    {"en":"energetic","zh":"精力充沛的","pos":"","notes":"","frequency":0},
    {"en":"active","zh":"活跃的,积极的","pos":"","notes":"","frequency":0},
    {"en":"encourage","zh":"鼓励","pos":"","notes":"","frequency":0},
    {"en":"believe","zh":"相信","pos":"","notes":"","frequency":0},
    {"en":"face","zh":"面临,面对","pos":"","notes":"","frequency":0},
    {"en":"secret","zh":"秘密","pos":"","notes":"","frequency":0},
    {"en":"keep secrets","zh":"保密","pos":"","notes":"","frequency":0},
    {"en":"worse","zh":"更差的","pos":"","notes":"","frequency":0},
    {"en":"worst","zh":"最差的","pos":"","notes":"","frequency":0},
    {"en":"height","zh":"身高,高度","pos":"","notes":"","frequency":0},
    {"en":"sec.","zh":"秒","pos":"","notes":"","frequency":0},
    {"en":"test","zh":"测验,考查,试验","pos":"","notes":"","frequency":0},
    {"en":"badminton","zh":"羽毛球运动","pos":"","notes":"","frequency":0},
    {"en":"however","zh":"然而","pos":"","notes":"","frequency":0},
    {"en":"balloon","zh":"气球","pos":"","notes":"","frequency":0},
    {"en":"scared","zh":"害怕,恐惧","pos":"","notes":"","frequency":0},
    {"en":"fight","zh":"搏斗,打斗,为……斗争","pos":"","notes":"","frequency":0},
    {"en":"dead","zh":"死的","pos":"","notes":"","frequency":0},
    {"en":"attack","zh":"攻击,袭击","pos":"","notes":"","frequency":0},
    {"en":"gone","zh":"离开了,不在","pos":"","notes":"","frequency":0},
    {"en":"danger","zh":"危险","pos":"","notes":"","frequency":0},
    {"en":"brave","zh":"勇敢的","pos":"","notes":"","frequency":0},
    {"en":"get along with some body","zh":"与某人和睦相处,关系良好","pos":"","notes":"","frequency":0},
    {"en":"listener","zh":"听者,听众","pos":"","notes":"","frequency":0},
    {"en":"nod","zh":"点头","pos":"","notes":"","frequency":0},
    {"en":"feeling","zh":"情感,感觉","pos":"","notes":"","frequency":0},
    {"en":"once","zh":"一……就,一旦","pos":"","notes":"","frequency":0},
    {"en":"patient","zh":"有耐心的","pos":"","notes":"","frequency":0},
    {"en":"thoughtful","zh":"体贴的,深思的","pos":"","notes":"","frequency":0},
    {"en":"secret","zh":"秘密的","pos":"","notes":"","frequency":0},
    {"en":"plastic","zh":"塑料的,塑料","pos":"","notes":"","frequency":0},
    {"en":"cheap","zh":"便宜的","pos":"","notes":"","frequency":0},
    {"en":"environment","zh":"环境","pos":"","notes":"","frequency":0},
    {"en":"few","zh":"不多,很少,很少人（或事物、地方）","pos":"","notes":"","frequency":0},
    {"en":"drama","zh":"戏剧,戏,剧","pos":"","notes":"","frequency":0},
    {"en":"foreign","zh":"外国的","pos":"","notes":"","frequency":0},
    {"en":"as","zh":"和……一样","pos":"","notes":"","frequency":0},
    {"en":"as ... as ...","zh":"和……一样……","pos":"","notes":"","frequency":0},
    {"en":"French","zh":"法语,法国人","pos":"","notes":"","frequency":0},
    {"en":"German","zh":"德语,德国人","pos":"","notes":"","frequency":0},
    {"en":"forward","zh":"向前","pos":"","notes":"","frequency":0},
    {"en":"look forward to","zh":"期待","pos":"","notes":"","frequency":0},
    {"en":"go","zh":"尝试","pos":"","notes":"","frequency":0},
    {"en":"have a go","zh":"尝试,试图","pos":"","notes":"","frequency":0},
    {"en":"earthquake","zh":"地震","pos":"","notes":"","frequency":0},
    {"en":"offer","zh":"提供","pos":"","notes":"","frequency":0},
    {"en":"programme ( program)","zh":"课程,计划,节目","pos":"","notes":"","frequency":0},
    {"en":"plenty","zh":"大量","pos":"","notes":"","frequency":0},
    {"en":"plenty of","zh":"大量","pos":"","notes":"","frequency":0},
    {"en":"hands-on","zh":"实际操作的","pos":"","notes":"","frequency":0},
    {"en":"attention","zh":"注意,专心,注意力","pos":"","notes":"","frequency":0},
    {"en":"pay attention to","zh":"注意","pos":"","notes":"","frequency":0},
    {"en":"aware","zh":"意识到,知道","pos":"","notes":"","frequency":0},
    {"en":"be aware of","zh":"意识到","pos":"","notes":"","frequency":0},
    {"en":"importance","zh":"重要性","pos":"","notes":"","frequency":0},
    {"en":"Japanese","zh":"日本（人）的,日语的","pos":"","notes":"","frequency":0},
    {"en":"ourselves","zh":"我们自己","pos":"","notes":"","frequency":0},
    {"en":"develop","zh":"形成,开发,（使）发展","pos":"","notes":"","frequency":0},
    {"en":"junior","zh":"初级的,青少年的","pos":"","notes":"","frequency":0},
    {"en":"rocket","zh":"火箭","pos":"","notes":"","frequency":0},
    {"en":"lunchtime","zh":"午餐时间","pos":"","notes":"","frequency":0},
    {"en":"least","zh":"最少的,最少","pos":"","notes":"","frequency":0},
    {"en":"international","zh":"国际（化）的","pos":"","notes":"","frequency":0},
    {"en":"vacation","zh":"（美）假期,度假","pos":"","notes":"","frequency":0},
    {"en":"textbook","zh":"课本,教材","pos":"","notes":"","frequency":0},
    {"en":"search","zh":"搜索,查找","pos":"","notes":"","frequency":0},
    {"en":"finish","zh":"完成,做好","pos":"","notes":"","frequency":0},
    {"en":"American","zh":"美国（人）的","pos":"","notes":"","frequency":0},
    {"en":"hamburger","zh":"汉堡包","pos":"","notes":"","frequency":0},
    {"en":"pizza","zh":"比萨饼","pos":"","notes":"","frequency":0},
    {"en":"fried","zh":"油炸的","pos":"","notes":"","frequency":0},
    {"en":"salad","zh":"沙拉","pos":"","notes":"","frequency":0},
    {"en":"chopstick","zh":"筷子","pos":"","notes":"","frequency":0},
    {"en":"movie","zh":"（美）电影","pos":"","notes":"","frequency":0},
    {"en":"difference","zh":"差异,不同（之处）","pos":"","notes":"","frequency":0},
    {"en":"cookie","zh":"（美）饼干","pos":"","notes":"","frequency":0},
    {"en":"fork","zh":"餐叉","pos":"","notes":"","frequency":0},
    {"en":"spoon","zh":"勺,匙","pos":"","notes":"","frequency":0},
    {"en":"boring","zh":"没趣的,令人厌倦的","pos":"","notes":"","frequency":0},
    {"en":"suggestion","zh":"建议","pos":"","notes":"","frequency":0},
    {"en":"uniform","zh":"校服,制服","pos":"","notes":"","frequency":0},
    {"en":"improve","zh":"改进,改善","pos":"","notes":"","frequency":0},
    {"en":"suggest","zh":"建议","pos":"","notes":"","frequency":0},
    {"en":"provide","zh":"提供","pos":"","notes":"","frequency":0},
    {"en":"moreover","zh":"此外","pos":"","notes":"","frequency":0},
    {"en":"yours sincerely","zh":"谨上,谨启","pos":"","notes":"","frequency":0},
    {"en":"learner","zh":"学习者","pos":"","notes":"","frequency":0},
    {"en":"feed","zh":"为……提供食物,喂养","pos":"","notes":"","frequency":0},
    {"en":"fish","zh":"钓鱼,捕鱼","pos":"","notes":"","frequency":0},
    {"en":"lifetime","zh":"一生,有生之年","pos":"","notes":"","frequency":0},
    {"en":"journey","zh":"旅程,旅行","pos":"","notes":"","frequency":0},
    {"en":"single","zh":"单个的,单身的","pos":"","notes":"","frequency":0},
    {"en":"against","zh":"逆,反对,紧靠","pos":"","notes":"","frequency":0},
    {"en":"fall behind","zh":"落后","pos":"","notes":"","frequency":0},
    {"en":"successful","zh":"有成效的,成功的","pos":"","notes":"","frequency":0},
    {"en":"drive","zh":"冲劲,本能需求","pos":"","notes":"","frequency":0},
    {"en":"guide","zh":"指导,给某人领路（或导游）","pos":"","notes":"","frequency":0},
    {"en":"lifelong","zh":"终身的","pos":"","notes":"","frequency":0},
    {"en":"inventor","zh":"发明家","pos":"","notes":"","frequency":0},
    {"en":"talent","zh":"天资,才能,有才能的人","pos":"","notes":"","frequency":0},
    {"en":"century","zh":"世纪,百年","pos":"","notes":"","frequency":0},
    {"en":"set ... apart","zh":"使……突出,使……与众不同","pos":"","notes":"","frequency":0},
    {"en":"print","zh":"印刷行业","pos":"","notes":"","frequency":0},
    {"en":"himself","zh":"他自己","pos":"","notes":"","frequency":0},
    {"en":"bookseller","zh":"书商","pos":"","notes":"","frequency":0},
    {"en":"in order to","zh":"为了","pos":"","notes":"","frequency":0},
    {"en":"return","zh":"归还","pos":"","notes":"","frequency":0},
    {"en":"curious","zh":"好奇的","pos":"","notes":"","frequency":0},
    {"en":"storm","zh":"暴风雨","pos":"","notes":"","frequency":0},
    {"en":"finding","zh":"调查发现","pos":"","notes":"","frequency":0},
    {"en":"predict","zh":"预测","pos":"","notes":"","frequency":0},
    {"en":"countless","zh":"数不尽的","pos":"","notes":"","frequency":0},
    {"en":"invention","zh":"发明","pos":"","notes":"","frequency":0},
    {"en":"come as no surprise","zh":"不足为奇","pos":"","notes":"","frequency":0},
    {"en":"invent","zh":"发明","pos":"","notes":"","frequency":0},
    {"en":"for free","zh":"免费","pos":"","notes":"","frequency":0},
    {"en":"greatness","zh":"伟大","pos":"","notes":"","frequency":0},
    {"en":"further","zh":"更远,较远","pos":"","notes":"","frequency":0},
    {"en":"success","zh":"成功","pos":"","notes":"","frequency":0},
    {"en":"Italian","zh":"意大利语,意大利人","pos":"","notes":"","frequency":0},
    {"en":"themselves","zh":"他们（她们,它们）自己","pos":"","notes":"","frequency":0},
    {"en":"conversation","zh":"交谈,谈话","pos":"","notes":"","frequency":0},
    {"en":"translate","zh":"翻译","pos":"","notes":"","frequency":0},
    {"en":"page","zh":"（书刊或纸张的）页","pos":"","notes":"","frequency":0},
    {"en":"badly","zh":"严重地,厉害地","pos":"","notes":"","frequency":0},
    {"en":"yourself","zh":"你自己","pos":"","notes":"","frequency":0},
    {"en":"yourselves","zh":"你们自己","pos":"","notes":"","frequency":0},
    {"en":"record","zh":"录制,记录","pos":"","notes":"","frequency":0},
    {"en":"printer","zh":"印刷工,印刷商,打印机","pos":"","notes":"","frequency":0},
    {"en":"dialect","zh":"方言","pos":"","notes":"","frequency":0},
    {"en":"besides","zh":"除……之外（还）","pos":"","notes":"","frequency":0},
    {"en":"possible","zh":"可能的","pos":"","notes":"","frequency":0},
    {"en":"as ... as possible","zh":"尽可能……","pos":"","notes":"","frequency":0},
    {"en":"sentence","zh":"句子","pos":"","notes":"","frequency":0},
    {"en":"rather than","zh":"而不是","pos":"","notes":"","frequency":0},
    {"en":"pronunciation","zh":"发音","pos":"","notes":"","frequency":0},
    {"en":"grammar","zh":"语法","pos":"","notes":"","frequency":0},
    {"en":"text","zh":"文本,文章","pos":"","notes":"","frequency":0},
    {"en":"slowly","zh":"慢速地,缓慢地","pos":"","notes":"","frequency":0},
    {"en":"whole","zh":"整个,全部","pos":"","notes":"","frequency":0},
    {"en":"speech","zh":"演讲,说话的能力","pos":"","notes":"","frequency":0},
    {"en":"aloud","zh":"出声地,大声地","pos":"","notes":"","frequency":0},
    {"en":"pronounce","zh":"发音","pos":"","notes":"","frequency":0},
    {"en":"correctly","zh":"正确地","pos":"","notes":"","frequency":0},
    {"en":"spelling","zh":"拼写","pos":"","notes":"","frequency":0},
    {"en":"nearby","zh":"在附近,附近的","pos":"","notes":"","frequency":0},
    {"en":"to one's surprise","zh":"令某人惊讶的是","pos":"","notes":"","frequency":0},
    {"en":"repeat","zh":"重复","pos":"","notes":"","frequency":0},
    {"en":"tourist","zh":"游客,观光者","pos":"","notes":"","frequency":0},
    {"en":"Moon cake","zh":"月饼","pos":"","notes":"","frequency":0},
    {"en":"shelf (pl. shelves)","zh":"架子","pos":"","notes":"","frequency":0},
    {"en":"rose","zh":"玫瑰（花）","pos":"","notes":"","frequency":0},
    {"en":"coloured paper","zh":"彩纸","pos":"","notes":"","frequency":0},
    {"en":"tape","zh":"胶带,用胶带粘贴","pos":"","notes":"","frequency":0},
    {"en":"glue","zh":"胶,胶水,（用胶水）黏合,粘贴","pos":"","notes":"","frequency":0},
    {"en":"fold","zh":"折叠","pos":"","notes":"","frequency":0},
    {"en":"complete","zh":"完成,结束,全部的","pos":"","notes":"","frequency":0},
    {"en":"DIY (= do-it-yourself)","zh":"自己动手","pos":"","notes":"","frequency":0},
    {"en":"crazy","zh":"狂热的,迷恋的","pos":"","notes":"","frequency":0},
    {"en":"be crazy about","zh":"热衷于","pos":"","notes":"","frequency":0},
    {"en":"born","zh":"天生的","pos":"","notes":"","frequency":0},
    {"en":"handyman (pl. handymen)","zh":"手巧的人","pos":"","notes":"","frequency":0},
    {"en":"mistake","zh":"错误","pos":"","notes":"","frequency":0},
    {"en":"power cut","zh":"断电,停电","pos":"","notes":"","frequency":0},
    {"en":"pipe","zh":"管道,管子","pos":"","notes":"","frequency":0},
    {"en":"fill ... with","zh":"使……充满","pos":"","notes":"","frequency":0},
    {"en":"unlucky","zh":"不幸的,不顺利的","pos":"","notes":"","frequency":0},
    {"en":"instead","zh":"反而","pos":"","notes":"","frequency":0},
    {"en":"course","zh":"课程","pos":"","notes":"","frequency":0},
    {"en":"mess","zh":"杂乱,不整洁","pos":"","notes":"","frequency":0},
    {"en":"in a mess","zh":"乱七八糟","pos":"","notes":"","frequency":0},
    {"en":"lamp","zh":"灯","pos":"","notes":"","frequency":0},
    {"en":"catch one's eye","zh":"引起某人注意","pos":"","notes":"","frequency":0},
    {"en":"surprised","zh":"惊奇的,感到意外的","pos":"","notes":"","frequency":0},
    {"en":"impossible","zh":"不可能的","pos":"","notes":"","frequency":0},
    {"en":"paint","zh":"油漆,绘画颜料","pos":"","notes":"","frequency":0},
    {"en":"can","zh":"金属容器,塑料容器","pos":"","notes":"","frequency":0},
    {"en":"everywhere","zh":"到处","pos":"","notes":"","frequency":0},
    {"en":"chalk","zh":"粉笔","pos":"","notes":"","frequency":0},
    {"en":"mark","zh":"标记,分数","pos":"","notes":"","frequency":0},
    {"en":"brush","zh":"刷子,画笔","pos":"","notes":"","frequency":0},
    {"en":"instructions","zh":"用法说明","pos":"","notes":"","frequency":0},
    {"en":"dangerous","zh":"危险的","pos":"","notes":"","frequency":0},
    {"en":"usual","zh":"通常的,寻常的","pos":"","notes":"","frequency":0},
    {"en":"tie-dye","zh":"扎染（织物）","pos":"","notes":"","frequency":0},
    {"en":"twist","zh":"使扭曲,使弯曲","pos":"","notes":"","frequency":0},
    {"en":"cloth","zh":"布料,织物","pos":"","notes":"","frequency":0},
    {"en":"tie","zh":"（用线,绳等）系,拴,绑,捆","pos":"","notes":"","frequency":0},
    {"en":"thread","zh":"线","pos":"","notes":"","frequency":0},
    {"en":"dye","zh":"给……染色,染,染料,染液","pos":"","notes":"","frequency":0},
    {"en":"untie","zh":"解开","pos":"","notes":"","frequency":0},
    {"en":"method","zh":"方法","pos":"","notes":"","frequency":0},
    {"en":"product","zh":"产品","pos":"","notes":"","frequency":0},
    {"en":"not only ... but also ...","zh":"不仅……而且……","pos":"","notes":"","frequency":0},
    {"en":"workshop","zh":"作坊","pos":"","notes":"","frequency":0},
    {"en":"dry","zh":"（使）变干,（把……）弄干","pos":"","notes":"","frequency":0},
    {"en":"pattern","zh":"图案,模式","pos":"","notes":"","frequency":0},
    {"en":"roll","zh":"卷,管","pos":"","notes":"","frequency":0},
    {"en":"reduce","zh":"减少","pos":"","notes":"","frequency":0},
    {"en":"waste","zh":"浪费,废料","pos":"","notes":"","frequency":0},
    {"en":"joy","zh":"高兴,乐趣","pos":"","notes":"","frequency":0},
    {"en":"glove","zh":"手套","pos":"","notes":"","frequency":0},
    {"en":"finger","zh":"（手套的）指部,手指","pos":"","notes":"","frequency":0},
    {"en":"button","zh":"纽扣,按钮","pos":"","notes":"","frequency":0},
    {"en":"onto","zh":"到……上,向……上","pos":"","notes":"","frequency":0},
    {"en":"wild","zh":"野生的,野生状态,自然环境","pos":"","notes":"","frequency":0},
    {"en":"dolphin","zh":"海豚","pos":"","notes":"","frequency":0},
    {"en":"eagle","zh":"雕","pos":"","notes":"","frequency":0},
    {"en":"fox","zh":"狐狸","pos":"","notes":"","frequency":0},
    {"en":"shark","zh":"鲨鱼","pos":"","notes":"","frequency":0},
    {"en":"wolf (pl. wolves)","zh":"狼","pos":"","notes":"","frequency":0},
    {"en":"zebra (pl. zebra, zebras)","zh":"斑马","pos":"","notes":"","frequency":0},
    {"en":"king","zh":"大王,国王","pos":"","notes":"","frequency":0},
    {"en":"tiny","zh":"极小的","pos":"","notes":"","frequency":0},
    {"en":"birth","zh":"出生","pos":"","notes":"","frequency":0},
    {"en":"round-the-clock","zh":"全天候的","pos":"","notes":"","frequency":0},
    {"en":"weigh","zh":"有……重","pos":"","notes":"","frequency":0},
    {"en":"satisfying","zh":"令人满意的","pos":"","notes":"","frequency":0},
    {"en":"giant panda","zh":"大熊猫","pos":"","notes":"","frequency":0},
    {"en":"in the wild","zh":"在野外","pos":"","notes":"","frequency":0},
    {"en":"serious","zh":"严重的","pos":"","notes":"","frequency":0},
    {"en":"even if","zh":"即使,尽管","pos":"","notes":"","frequency":0},
    {"en":"easily","zh":"很可能,容易地","pos":"","notes":"","frequency":0},
    {"en":"sick","zh":"生病的","pos":"","notes":"","frequency":0},
    {"en":"live on","zh":"以吃……为生","pos":"","notes":"","frequency":0},
    {"en":"mainly","zh":"主要地","pos":"","notes":"","frequency":0},
    {"en":"result","zh":"结果,后果","pos":"","notes":"","frequency":0},
    {"en":"as a result","zh":"因此","pos":"","notes":"","frequency":0},
    {"en":"government","zh":"政府","pos":"","notes":"","frequency":0},
    {"en":"action","zh":"行动","pos":"","notes":"","frequency":0},
    {"en":"take action","zh":"采取行动","pos":"","notes":"","frequency":0},
    {"en":"nature reserve","zh":"自然保护区","pos":"","notes":"","frequency":0},
    {"en":"thanks to","zh":"多亏,由于","pos":"","notes":"","frequency":0},
    {"en":"effort","zh":"努力","pos":"","notes":"","frequency":0},
    {"en":"increase","zh":"增加","pos":"","notes":"","frequency":0},
    {"en":"protection","zh":"保护","pos":"","notes":"","frequency":0},
    {"en":"growth","zh":"生长,发育,成长","pos":"","notes":"","frequency":0},
    {"en":"fat","zh":"胖的","pos":"","notes":"","frequency":0},
    {"en":"manage","zh":"完成（困难的事）","pos":"","notes":"","frequency":0},
    {"en":"whale","zh":"鲸","pos":"","notes":"","frequency":0},
    {"en":"hunt","zh":"猎杀","pos":"","notes":"","frequency":0},
    {"en":"meaningful","zh":"重要的","pos":"","notes":"","frequency":0},
    {"en":"in danger","zh":"处于危险中","pos":"","notes":"","frequency":0},
    {"en":"reason","zh":"理由,原因","pos":"","notes":"","frequency":0},
    {"en":"accept","zh":"收受,接受","pos":"","notes":"","frequency":0},
    {"en":"polar bear","zh":"北极熊","pos":"","notes":"","frequency":0},
    {"en":"meat eater","zh":"肉食动物（或人）","pos":"","notes":"","frequency":0},
    {"en":"melt","zh":"（使）融化","pos":"","notes":"","frequency":0},
    {"en":"drop","zh":"（使）降低,扔下,掉下","pos":"","notes":"","frequency":0},
    {"en":"blue whale","zh":"蓝鲸","pos":"","notes":"","frequency":0},
    {"en":"risk","zh":"危险,风险","pos":"","notes":"","frequency":0},
    {"en":"at risk","zh":"有危险","pos":"","notes":"","frequency":0},
    {"en":"Indian","zh":"印度（人）的","pos":"","notes":"","frequency":0},
    {"en":"rhino","zh":"犀牛","pos":"","notes":"","frequency":0},
    {"en":"horn","zh":"角","pos":"","notes":"","frequency":0},
    {"en":"disaster","zh":"灾害","pos":"","notes":"","frequency":0},
    {"en":"pollution","zh":"污染","pos":"","notes":"","frequency":0},
    {"en":"certain","zh":"某种,某些","pos":"","notes":"","frequency":0},
    {"en":"illness","zh":"疾病,病","pos":"","notes":"","frequency":0},
    {"en":"foggy","zh":"有雾的,雾茫茫的","pos":"","notes":"","frequency":0},
    {"en":"snowy","zh":"下雪多的,被雪覆盖的","pos":"","notes":"","frequency":0},
    {"en":"pleasant","zh":"令人愉快的","pos":"","notes":"","frequency":0},
    {"en":"yeah","zh":"是的","pos":"","notes":"","frequency":0},
    {"en":"hide","zh":"躲避,藏","pos":"","notes":"","frequency":0},
    {"en":"shower","zh":"阵雨","pos":"","notes":"","frequency":0},
    {"en":"memory","zh":"回忆","pos":"","notes":"","frequency":0},
    {"en":"stream","zh":"小河,溪","pos":"","notes":"","frequency":0},
    {"en":"shade","zh":"（树）荫","pos":"","notes":"","frequency":0},
    {"en":"lazy","zh":"慵懒的,懒惰的","pos":"","notes":"","frequency":0},
    {"en":"pool","zh":"水塘,池塘","pos":"","notes":"","frequency":0},
    {"en":"pile","zh":"堆","pos":"","notes":"","frequency":0},
    {"en":"upon","zh":"在……上","pos":"","notes":"","frequency":0},
    {"en":"harvest","zh":"收割（庄稼）","pos":"","notes":"","frequency":0},
    {"en":"crop","zh":"庄稼,作物","pos":"","notes":"","frequency":0},
    {"en":"as","zh":"当……时,随着,因为","pos":"","notes":"","frequency":0},
    {"en":"temperature","zh":"温度","pos":"","notes":"","frequency":0},
    {"en":"sofa","zh":"长沙发","pos":"","notes":"","frequency":0},
    {"en":"snowman (pl. snowmen)","zh":"雪人","pos":"","notes":"","frequency":0},
    {"en":"blow","zh":"吹,刮,吹（气）","pos":"","notes":"","frequency":0},
    {"en":"shine","zh":"发光,照耀","pos":"","notes":"","frequency":0},
    {"en":"smell","zh":"有（或发出）……气味","pos":"","notes":"","frequency":0},
    {"en":"heat","zh":"热,热量","pos":"","notes":"","frequency":0},
    {"en":"sudden","zh":"突然的","pos":"","notes":"","frequency":0},
    {"en":"snowball","zh":"雪球","pos":"","notes":"","frequency":0},
    {"en":"fog","zh":"雾","pos":"","notes":"","frequency":0},
    {"en":"divide","zh":"（使）分开,分成","pos":"","notes":"","frequency":0},
    {"en":"divide ... into ...","zh":"把……分成……","pos":"","notes":"","frequency":0},
    {"en":"end","zh":"结束,终止","pos":"","notes":"","frequency":0},
    {"en":"beyond","zh":"超出,除……之外","pos":"","notes":"","frequency":0},
    {"en":"connect","zh":"把……联系起来,（使）连接","pos":"","notes":"","frequency":0},
    {"en":"be connected with","zh":"与……有联系","pos":"","notes":"","frequency":0},
    {"en":"positive","zh":"正面的,积极的,肯定的","pos":"","notes":"","frequency":0},
    {"en":"effect","zh":"影响,结果,效果","pos":"","notes":"","frequency":0},
    {"en":"average","zh":"平均的","pos":"","notes":"","frequency":0},
    {"en":"wet","zh":"湿的,潮的","pos":"","notes":"","frequency":0},
    {"en":"daylight","zh":"日光","pos":"","notes":"","frequency":0},
    {"en":"degree","zh":"度,度数","pos":"","notes":"","frequency":0},
    {"en":"on average","zh":"平均","pos":"","notes":"","frequency":0},
    {"en":"sunshine","zh":"阳光","pos":"","notes":"","frequency":0},
    {"en":"start","zh":"开头,开端","pos":"","notes":"","frequency":0},
    {"en":"snowstorm","zh":"雪暴,暴风雪","pos":"","notes":"","frequency":0},
    {"en":"awful","zh":"糟糕的,极讨厌的","pos":"","notes":"","frequency":0},
    {"en":"order","zh":"订购","pos":"","notes":"","frequency":0},
    {"en":"take care","zh":"保重","pos":"","notes":"","frequency":0},
    {"en":"frozen","zh":"结冰的,冷冻的","pos":"","notes":"","frequency":0},
    {"en":"thick","zh":"厚的,浓的","pos":"","notes":"","frequency":0},
    {"en":"deep","zh":"厚的,深的","pos":"","notes":"","frequency":0},
    {"en":"throw","zh":"扔","pos":"","notes":"","frequency":0},
    {"en":"sculpture","zh":"雕像,雕塑品译林英语八年级上册 Unit 1-6 单词表","pos":"","notes":"","frequency":0},
    {"en":"friendship","zh":"友谊","pos":"","notes":"","frequency":0},
    {"en":"honest","zh":"诚实的,正直的","pos":"","notes":"","frequency":0},
    {"en":"cheerful","zh":"快乐的,乐观的","pos":"","notes":"","frequency":0},
    {"en":"humorous","zh":"幽默的","pos":"","notes":"","frequency":0},
    {"en":"caring","zh":"关心他人的,体贴人的","pos":"","notes":"","frequency":0},
    {"en":"truth","zh":"事实","pos":"","notes":"","frequency":0},
    {"en":"joke","zh":"笑话,玩笑","pos":"","notes":"","frequency":0},
    {"en":"laugh","zh":"笑,发笑","pos":"","notes":"","frequency":0},
    {"en":"teenager","zh":"青少年","pos":"","notes":"","frequency":0},
    {"en":"unhappy","zh":"不开心的","pos":"","notes":"","frequency":0},
    {"en":"lie","zh":"撒谎","pos":"","notes":"","frequency":0},
    {"en":"person","zh":"人,个人","pos":"","notes":"","frequency":0},
    {"en":"thought","zh":"想法,主意","pos":"","notes":"","frequency":0},
    {"en":"ponytail","zh":"马尾辫","pos":"","notes":"","frequency":0},
    {"en":"seat","zh":"座位","pos":"","notes":"","frequency":0},
    {"en":"schoolwork","zh":"学校作业","pos":"","notes":"","frequency":0},
    {"en":"trustworthy","zh":"值得信赖的","pos":"","notes":"","frequency":0},
    {"en":"carefully","zh":"仔细地,小心地","pos":"","notes":"","frequency":0},
    {"en":"understand","zh":"理解","pos":"","notes":"","frequency":0},
    {"en":"bit","zh":"少量","pos":"","notes":"","frequency":0},
    {"en":"a little bit","zh":"有点儿","pos":"","notes":"","frequency":0},
    {"en":"funny","zh":"好笑的","pos":"","notes":"","frequency":0},
    {"en":"sense","zh":"理解力,感觉","pos":"","notes":"","frequency":0},
    {"en":"humour ( humor)","zh":"幽默","pos":"","notes":"","frequency":0},
    {"en":"sense of humour","zh":"幽默感","pos":"","notes":"","frequency":0},
    {"en":"bored","zh":"厌倦的,烦闷的","pos":"","notes":"","frequency":0},
    {"en":"energetic","zh":"精力充沛的","pos":"","notes":"","frequency":0},
    {"en":"active","zh":"活跃的,积极的","pos":"","notes":"","frequency":0},
    {"en":"encourage","zh":"鼓励","pos":"","notes":"","frequency":0},
    {"en":"believe","zh":"相信","pos":"","notes":"","frequency":0},
    {"en":"face","zh":"面临,面对","pos":"","notes":"","frequency":0},
    {"en":"secret","zh":"秘密","pos":"","notes":"","frequency":0},
    {"en":"keep secrets","zh":"保密","pos":"","notes":"","frequency":0},
    {"en":"worse","zh":"更差的","pos":"","notes":"","frequency":0},
    {"en":"worst","zh":"最差的","pos":"","notes":"","frequency":0},
    {"en":"height","zh":"身高,高度","pos":"","notes":"","frequency":0},
    {"en":"sec.","zh":"秒","pos":"","notes":"","frequency":0},
    {"en":"test","zh":"测验,考查,试验","pos":"","notes":"","frequency":0},
    {"en":"badminton","zh":"羽毛球运动","pos":"","notes":"","frequency":0},
    {"en":"however","zh":"然而","pos":"","notes":"","frequency":0},
    {"en":"balloon","zh":"气球","pos":"","notes":"","frequency":0},
    {"en":"scared","zh":"害怕,恐惧","pos":"","notes":"","frequency":0},
    {"en":"fight","zh":"搏斗,打斗,为……斗争","pos":"","notes":"","frequency":0},
    {"en":"dead","zh":"死的","pos":"","notes":"","frequency":0},
    {"en":"attack","zh":"攻击,袭击","pos":"","notes":"","frequency":0},
    {"en":"gone","zh":"离开了,不在","pos":"","notes":"","frequency":0},
    {"en":"danger","zh":"危险","pos":"","notes":"","frequency":0},
    {"en":"brave","zh":"勇敢的","pos":"","notes":"","frequency":0},
    {"en":"get along with some body","zh":"与某人和睦相处,关系良好","pos":"","notes":"","frequency":0},
    {"en":"listener","zh":"听者,听众","pos":"","notes":"","frequency":0},
    {"en":"nod","zh":"点头","pos":"","notes":"","frequency":0},
    {"en":"feeling","zh":"情感,感觉","pos":"","notes":"","frequency":0},
    {"en":"once","zh":"一……就,一旦","pos":"","notes":"","frequency":0},
    {"en":"patient","zh":"有耐心的","pos":"","notes":"","frequency":0},
    {"en":"thoughtful","zh":"体贴的,深思的","pos":"","notes":"","frequency":0},
    {"en":"secret","zh":"秘密的","pos":"","notes":"","frequency":0},
    {"en":"plastic","zh":"塑料的,塑料","pos":"","notes":"","frequency":0},
    {"en":"cheap","zh":"便宜的","pos":"","notes":"","frequency":0},
    {"en":"environment","zh":"环境","pos":"","notes":"","frequency":0},
    {"en":"few","zh":"不多,很少,很少人（或事物、地方）","pos":"","notes":"","frequency":0},
    {"en":"drama","zh":"戏剧,戏,剧","pos":"","notes":"","frequency":0},
    {"en":"foreign","zh":"外国的","pos":"","notes":"","frequency":0},
    {"en":"as","zh":"和……一样","pos":"","notes":"","frequency":0},
    {"en":"as ... as ...","zh":"和……一样……","pos":"","notes":"","frequency":0},
    {"en":"French","zh":"法语,法国人","pos":"","notes":"","frequency":0},
    {"en":"German","zh":"德语,德国人","pos":"","notes":"","frequency":0},
    {"en":"forward","zh":"向前","pos":"","notes":"","frequency":0},
    {"en":"look forward to","zh":"期待","pos":"","notes":"","frequency":0},
    {"en":"go","zh":"尝试","pos":"","notes":"","frequency":0},
    {"en":"have a go","zh":"尝试,试图","pos":"","notes":"","frequency":0},
    {"en":"earthquake","zh":"地震","pos":"","notes":"","frequency":0},
    {"en":"offer","zh":"提供","pos":"","notes":"","frequency":0},
    {"en":"programme ( program)","zh":"课程,计划,节目","pos":"","notes":"","frequency":0},
    {"en":"plenty","zh":"大量","pos":"","notes":"","frequency":0},
    {"en":"plenty of","zh":"大量","pos":"","notes":"","frequency":0},
    {"en":"hands-on","zh":"实际操作的","pos":"","notes":"","frequency":0},
    {"en":"attention","zh":"注意,专心,注意力","pos":"","notes":"","frequency":0},
    {"en":"pay attention to","zh":"注意","pos":"","notes":"","frequency":0},
    {"en":"aware","zh":"意识到,知道","pos":"","notes":"","frequency":0},
    {"en":"be aware of","zh":"意识到","pos":"","notes":"","frequency":0},
    {"en":"importance","zh":"重要性","pos":"","notes":"","frequency":0},
    {"en":"Japanese","zh":"日本（人）的,日语的","pos":"","notes":"","frequency":0},
    {"en":"ourselves","zh":"我们自己","pos":"","notes":"","frequency":0},
    {"en":"develop","zh":"形成,开发,（使）发展","pos":"","notes":"","frequency":0},
    {"en":"junior","zh":"初级的,青少年的","pos":"","notes":"","frequency":0},
    {"en":"rocket","zh":"火箭","pos":"","notes":"","frequency":0},
    {"en":"lunchtime","zh":"午餐时间","pos":"","notes":"","frequency":0},
    {"en":"least","zh":"最少的,最少","pos":"","notes":"","frequency":0},
    {"en":"international","zh":"国际（化）的","pos":"","notes":"","frequency":0},
    {"en":"vacation","zh":"（美）假期,度假","pos":"","notes":"","frequency":0},
    {"en":"textbook","zh":"课本,教材","pos":"","notes":"","frequency":0},
    {"en":"search","zh":"搜索,查找","pos":"","notes":"","frequency":0},
    {"en":"finish","zh":"完成,做好","pos":"","notes":"","frequency":0},
    {"en":"American","zh":"美国（人）的","pos":"","notes":"","frequency":0},
    {"en":"hamburger","zh":"汉堡包","pos":"","notes":"","frequency":0},
    {"en":"pizza","zh":"比萨饼","pos":"","notes":"","frequency":0},
    {"en":"fried","zh":"油炸的","pos":"","notes":"","frequency":0},
    {"en":"salad","zh":"沙拉","pos":"","notes":"","frequency":0},
    {"en":"chopstick","zh":"筷子","pos":"","notes":"","frequency":0},
    {"en":"movie","zh":"（美）电影","pos":"","notes":"","frequency":0},
    {"en":"difference","zh":"差异,不同（之处）","pos":"","notes":"","frequency":0},
    {"en":"cookie","zh":"（美）饼干","pos":"","notes":"","frequency":0},
    {"en":"fork","zh":"餐叉","pos":"","notes":"","frequency":0},
    {"en":"spoon","zh":"勺,匙","pos":"","notes":"","frequency":0},
    {"en":"boring","zh":"没趣的,令人厌倦的","pos":"","notes":"","frequency":0},
    {"en":"suggestion","zh":"建议","pos":"","notes":"","frequency":0},
    {"en":"uniform","zh":"校服,制服","pos":"","notes":"","frequency":0},
    {"en":"improve","zh":"改进,改善","pos":"","notes":"","frequency":0},
    {"en":"suggest","zh":"建议","pos":"","notes":"","frequency":0},
    {"en":"provide","zh":"提供","pos":"","notes":"","frequency":0},
    {"en":"moreover","zh":"此外","pos":"","notes":"","frequency":0},
    {"en":"yours sincerely","zh":"谨上,谨启","pos":"","notes":"","frequency":0},
    {"en":"learner","zh":"学习者","pos":"","notes":"","frequency":0},
    {"en":"feed","zh":"为……提供食物,喂养","pos":"","notes":"","frequency":0},
    {"en":"fish","zh":"钓鱼,捕鱼","pos":"","notes":"","frequency":0},
    {"en":"lifetime","zh":"一生,有生之年","pos":"","notes":"","frequency":0},
    {"en":"journey","zh":"旅程,旅行","pos":"","notes":"","frequency":0},
    {"en":"single","zh":"单个的,单身的","pos":"","notes":"","frequency":0},
    {"en":"against","zh":"逆,反对,紧靠","pos":"","notes":"","frequency":0},
    {"en":"fall behind","zh":"落后","pos":"","notes":"","frequency":0},
    {"en":"successful","zh":"有成效的,成功的","pos":"","notes":"","frequency":0},
    {"en":"drive","zh":"冲劲,本能需求","pos":"","notes":"","frequency":0},
    {"en":"guide","zh":"指导,给某人领路（或导游）","pos":"","notes":"","frequency":0},
    {"en":"lifelong","zh":"终身的","pos":"","notes":"","frequency":0},
    {"en":"inventor","zh":"发明家","pos":"","notes":"","frequency":0},
    {"en":"talent","zh":"天资,才能,有才能的人","pos":"","notes":"","frequency":0},
    {"en":"century","zh":"世纪,百年","pos":"","notes":"","frequency":0},
    {"en":"set ... apart","zh":"使……突出,使……与众不同","pos":"","notes":"","frequency":0},
    {"en":"print","zh":"印刷行业","pos":"","notes":"","frequency":0},
    {"en":"himself","zh":"他自己","pos":"","notes":"","frequency":0},
    {"en":"bookseller","zh":"书商","pos":"","notes":"","frequency":0},
    {"en":"in order to","zh":"为了","pos":"","notes":"","frequency":0},
    {"en":"return","zh":"归还","pos":"","notes":"","frequency":0},
    {"en":"curious","zh":"好奇的","pos":"","notes":"","frequency":0},
    {"en":"storm","zh":"暴风雨","pos":"","notes":"","frequency":0},
    {"en":"finding","zh":"调查发现","pos":"","notes":"","frequency":0},
    {"en":"predict","zh":"预测","pos":"","notes":"","frequency":0},
    {"en":"countless","zh":"数不尽的","pos":"","notes":"","frequency":0},
    {"en":"invention","zh":"发明","pos":"","notes":"","frequency":0},
    {"en":"come as no surprise","zh":"不足为奇","pos":"","notes":"","frequency":0},
    {"en":"invent","zh":"发明","pos":"","notes":"","frequency":0},
    {"en":"for free","zh":"免费","pos":"","notes":"","frequency":0},
    {"en":"greatness","zh":"伟大","pos":"","notes":"","frequency":0},
    {"en":"further","zh":"更远,较远","pos":"","notes":"","frequency":0},
    {"en":"success","zh":"成功","pos":"","notes":"","frequency":0},
    {"en":"Italian","zh":"意大利语,意大利人","pos":"","notes":"","frequency":0},
    {"en":"themselves","zh":"他们（她们,它们）自己","pos":"","notes":"","frequency":0},
    {"en":"conversation","zh":"交谈,谈话","pos":"","notes":"","frequency":0},
    {"en":"translate","zh":"翻译","pos":"","notes":"","frequency":0},
    {"en":"page","zh":"（书刊或纸张的）页","pos":"","notes":"","frequency":0},
    {"en":"badly","zh":"严重地,厉害地","pos":"","notes":"","frequency":0},
    {"en":"yourself","zh":"你自己","pos":"","notes":"","frequency":0},
    {"en":"yourselves","zh":"你们自己","pos":"","notes":"","frequency":0},
    {"en":"record","zh":"录制,记录","pos":"","notes":"","frequency":0},
    {"en":"printer","zh":"印刷工,印刷商,打印机","pos":"","notes":"","frequency":0},
    {"en":"dialect","zh":"方言","pos":"","notes":"","frequency":0},
    {"en":"besides","zh":"除……之外（还）","pos":"","notes":"","frequency":0},
    {"en":"possible","zh":"可能的","pos":"","notes":"","frequency":0},
    {"en":"as ... as possible","zh":"尽可能……","pos":"","notes":"","frequency":0},
    {"en":"sentence","zh":"句子","pos":"","notes":"","frequency":0},
    {"en":"rather than","zh":"而不是","pos":"","notes":"","frequency":0},
    {"en":"pronunciation","zh":"发音","pos":"","notes":"","frequency":0},
    {"en":"grammar","zh":"语法","pos":"","notes":"","frequency":0},
    {"en":"text","zh":"文本,文章","pos":"","notes":"","frequency":0},
    {"en":"slowly","zh":"慢速地,缓慢地","pos":"","notes":"","frequency":0},
    {"en":"whole","zh":"整个,全部","pos":"","notes":"","frequency":0},
    {"en":"speech","zh":"演讲,说话的能力","pos":"","notes":"","frequency":0},
    {"en":"aloud","zh":"出声地,大声地","pos":"","notes":"","frequency":0},
    {"en":"pronounce","zh":"发音","pos":"","notes":"","frequency":0},
    {"en":"correctly","zh":"正确地","pos":"","notes":"","frequency":0},
    {"en":"spelling","zh":"拼写","pos":"","notes":"","frequency":0},
    {"en":"nearby","zh":"在附近,附近的","pos":"","notes":"","frequency":0},
    {"en":"to one's surprise","zh":"令某人惊讶的是","pos":"","notes":"","frequency":0},
    {"en":"repeat","zh":"重复","pos":"","notes":"","frequency":0},
    {"en":"tourist","zh":"游客,观光者","pos":"","notes":"","frequency":0},
    {"en":"Moon cake","zh":"月饼","pos":"","notes":"","frequency":0},
    {"en":"shelf (pl. shelves)","zh":"架子","pos":"","notes":"","frequency":0},
    {"en":"rose","zh":"玫瑰（花）","pos":"","notes":"","frequency":0},
    {"en":"coloured paper","zh":"彩纸","pos":"","notes":"","frequency":0},
    {"en":"tape","zh":"胶带,用胶带粘贴","pos":"","notes":"","frequency":0},
    {"en":"glue","zh":"胶,胶水,（用胶水）黏合,粘贴","pos":"","notes":"","frequency":0},
    {"en":"fold","zh":"折叠","pos":"","notes":"","frequency":0},
    {"en":"complete","zh":"完成,结束,全部的","pos":"","notes":"","frequency":0},
    {"en":"DIY (= do-it-yourself)","zh":"自己动手","pos":"","notes":"","frequency":0},
    {"en":"crazy","zh":"狂热的,迷恋的","pos":"","notes":"","frequency":0},
    {"en":"be crazy about","zh":"热衷于","pos":"","notes":"","frequency":0},
    {"en":"born","zh":"天生的","pos":"","notes":"","frequency":0},
    {"en":"handyman (pl. handymen)","zh":"手巧的人","pos":"","notes":"","frequency":0},
    {"en":"mistake","zh":"错误","pos":"","notes":"","frequency":0},
    {"en":"power cut","zh":"断电,停电","pos":"","notes":"","frequency":0},
    {"en":"pipe","zh":"管道,管子","pos":"","notes":"","frequency":0},
    {"en":"fill ... with","zh":"使……充满","pos":"","notes":"","frequency":0},
    {"en":"unlucky","zh":"不幸的,不顺利的","pos":"","notes":"","frequency":0},
    {"en":"instead","zh":"反而","pos":"","notes":"","frequency":0},
    {"en":"course","zh":"课程","pos":"","notes":"","frequency":0},
    {"en":"mess","zh":"杂乱,不整洁","pos":"","notes":"","frequency":0},
    {"en":"in a mess","zh":"乱七八糟","pos":"","notes":"","frequency":0},
    {"en":"lamp","zh":"灯","pos":"","notes":"","frequency":0},
    {"en":"catch one's eye","zh":"引起某人注意","pos":"","notes":"","frequency":0},
    {"en":"surprised","zh":"惊奇的,感到意外的","pos":"","notes":"","frequency":0},
    {"en":"impossible","zh":"不可能的","pos":"","notes":"","frequency":0},
    {"en":"paint","zh":"油漆,绘画颜料","pos":"","notes":"","frequency":0},
    {"en":"can","zh":"金属容器,塑料容器","pos":"","notes":"","frequency":0},
    {"en":"everywhere","zh":"到处","pos":"","notes":"","frequency":0},
    {"en":"chalk","zh":"粉笔","pos":"","notes":"","frequency":0},
    {"en":"mark","zh":"标记,分数","pos":"","notes":"","frequency":0},
    {"en":"brush","zh":"刷子,画笔","pos":"","notes":"","frequency":0},
    {"en":"instructions","zh":"用法说明","pos":"","notes":"","frequency":0},
    {"en":"dangerous","zh":"危险的","pos":"","notes":"","frequency":0},
    {"en":"usual","zh":"通常的,寻常的","pos":"","notes":"","frequency":0},
    {"en":"tie-dye","zh":"扎染（织物）","pos":"","notes":"","frequency":0},
    {"en":"twist","zh":"使扭曲,使弯曲","pos":"","notes":"","frequency":0},
    {"en":"cloth","zh":"布料,织物","pos":"","notes":"","frequency":0},
    {"en":"tie","zh":"（用线,绳等）系,拴,绑,捆","pos":"","notes":"","frequency":0},
    {"en":"thread","zh":"线","pos":"","notes":"","frequency":0},
    {"en":"dye","zh":"给……染色,染,染料,染液","pos":"","notes":"","frequency":0},
    {"en":"untie","zh":"解开","pos":"","notes":"","frequency":0},
    {"en":"method","zh":"方法","pos":"","notes":"","frequency":0},
    {"en":"product","zh":"产品","pos":"","notes":"","frequency":0},
    {"en":"not only ... but also ...","zh":"不仅……而且……","pos":"","notes":"","frequency":0},
    {"en":"workshop","zh":"作坊","pos":"","notes":"","frequency":0},
    {"en":"dry","zh":"（使）变干,（把……）弄干","pos":"","notes":"","frequency":0},
    {"en":"pattern","zh":"图案,模式","pos":"","notes":"","frequency":0},
    {"en":"roll","zh":"卷,管","pos":"","notes":"","frequency":0},
    {"en":"reduce","zh":"减少","pos":"","notes":"","frequency":0},
    {"en":"waste","zh":"浪费,废料","pos":"","notes":"","frequency":0},
    {"en":"joy","zh":"高兴,乐趣","pos":"","notes":"","frequency":0},
    {"en":"glove","zh":"手套","pos":"","notes":"","frequency":0},
    {"en":"finger","zh":"（手套的）指部,手指","pos":"","notes":"","frequency":0},
    {"en":"button","zh":"纽扣,按钮","pos":"","notes":"","frequency":0},
    {"en":"onto","zh":"到……上,向……上","pos":"","notes":"","frequency":0},
    {"en":"wild","zh":"野生的,野生状态,自然环境","pos":"","notes":"","frequency":0},
    {"en":"dolphin","zh":"海豚","pos":"","notes":"","frequency":0},
    {"en":"eagle","zh":"雕","pos":"","notes":"","frequency":0},
    {"en":"fox","zh":"狐狸","pos":"","notes":"","frequency":0},
    {"en":"shark","zh":"鲨鱼","pos":"","notes":"","frequency":0},
    {"en":"wolf (pl. wolves)","zh":"狼","pos":"","notes":"","frequency":0},
    {"en":"zebra (pl. zebra, zebras)","zh":"斑马","pos":"","notes":"","frequency":0},
    {"en":"king","zh":"大王,国王","pos":"","notes":"","frequency":0},
    {"en":"tiny","zh":"极小的","pos":"","notes":"","frequency":0},
    {"en":"birth","zh":"出生","pos":"","notes":"","frequency":0},
    {"en":"round-the-clock","zh":"全天候的","pos":"","notes":"","frequency":0},
    {"en":"weigh","zh":"有……重","pos":"","notes":"","frequency":0},
    {"en":"satisfying","zh":"令人满意的","pos":"","notes":"","frequency":0},
    {"en":"giant panda","zh":"大熊猫","pos":"","notes":"","frequency":0},
    {"en":"in the wild","zh":"在野外","pos":"","notes":"","frequency":0},
    {"en":"serious","zh":"严重的","pos":"","notes":"","frequency":0},
    {"en":"even if","zh":"即使,尽管","pos":"","notes":"","frequency":0},
    {"en":"easily","zh":"很可能,容易地","pos":"","notes":"","frequency":0},
    {"en":"sick","zh":"生病的","pos":"","notes":"","frequency":0},
    {"en":"live on","zh":"以吃……为生","pos":"","notes":"","frequency":0},
    {"en":"mainly","zh":"主要地","pos":"","notes":"","frequency":0},
    {"en":"result","zh":"结果,后果","pos":"","notes":"","frequency":0},
    {"en":"as a result","zh":"因此","pos":"","notes":"","frequency":0},
    {"en":"government","zh":"政府","pos":"","notes":"","frequency":0},
    {"en":"action","zh":"行动","pos":"","notes":"","frequency":0},
    {"en":"take action","zh":"采取行动","pos":"","notes":"","frequency":0},
    {"en":"nature reserve","zh":"自然保护区","pos":"","notes":"","frequency":0},
    {"en":"thanks to","zh":"多亏,由于","pos":"","notes":"","frequency":0},
    {"en":"effort","zh":"努力","pos":"","notes":"","frequency":0},
    {"en":"increase","zh":"增加","pos":"","notes":"","frequency":0},
    {"en":"protection","zh":"保护","pos":"","notes":"","frequency":0},
    {"en":"growth","zh":"生长,发育,成长","pos":"","notes":"","frequency":0},
    {"en":"fat","zh":"胖的","pos":"","notes":"","frequency":0},
    {"en":"manage","zh":"完成（困难的事）","pos":"","notes":"","frequency":0},
    {"en":"whale","zh":"鲸","pos":"","notes":"","frequency":0},
    {"en":"hunt","zh":"猎杀","pos":"","notes":"","frequency":0},
    {"en":"meaningful","zh":"重要的","pos":"","notes":"","frequency":0},
    {"en":"in danger","zh":"处于危险中","pos":"","notes":"","frequency":0},
    {"en":"reason","zh":"理由,原因","pos":"","notes":"","frequency":0},
    {"en":"accept","zh":"收受,接受","pos":"","notes":"","frequency":0},
    {"en":"polar bear","zh":"北极熊","pos":"","notes":"","frequency":0},
    {"en":"meat eater","zh":"肉食动物（或人）","pos":"","notes":"","frequency":0},
    {"en":"melt","zh":"（使）融化","pos":"","notes":"","frequency":0},
    {"en":"drop","zh":"（使）降低,扔下,掉下","pos":"","notes":"","frequency":0},
    {"en":"blue whale","zh":"蓝鲸","pos":"","notes":"","frequency":0},
    {"en":"risk","zh":"危险,风险","pos":"","notes":"","frequency":0},
    {"en":"at risk","zh":"有危险","pos":"","notes":"","frequency":0},
    {"en":"Indian","zh":"印度（人）的","pos":"","notes":"","frequency":0},
    {"en":"rhino","zh":"犀牛","pos":"","notes":"","frequency":0},
    {"en":"horn","zh":"角","pos":"","notes":"","frequency":0},
    {"en":"disaster","zh":"灾害","pos":"","notes":"","frequency":0},
    {"en":"pollution","zh":"污染","pos":"","notes":"","frequency":0},
    {"en":"certain","zh":"某种,某些","pos":"","notes":"","frequency":0},
    {"en":"illness","zh":"疾病,病","pos":"","notes":"","frequency":0},
    {"en":"foggy","zh":"有雾的,雾茫茫的","pos":"","notes":"","frequency":0},
    {"en":"snowy","zh":"下雪多的,被雪覆盖的","pos":"","notes":"","frequency":0},
    {"en":"pleasant","zh":"令人愉快的","pos":"","notes":"","frequency":0},
    {"en":"yeah","zh":"是的","pos":"","notes":"","frequency":0},
    {"en":"hide","zh":"躲避,藏","pos":"","notes":"","frequency":0},
    {"en":"shower","zh":"阵雨","pos":"","notes":"","frequency":0},
    {"en":"memory","zh":"回忆","pos":"","notes":"","frequency":0},
    {"en":"stream","zh":"小河,溪","pos":"","notes":"","frequency":0},
    {"en":"shade","zh":"（树）荫","pos":"","notes":"","frequency":0},
    {"en":"lazy","zh":"慵懒的,懒惰的","pos":"","notes":"","frequency":0},
    {"en":"pool","zh":"水塘,池塘","pos":"","notes":"","frequency":0},
    {"en":"pile","zh":"堆","pos":"","notes":"","frequency":0},
    {"en":"upon","zh":"在……上","pos":"","notes":"","frequency":0},
    {"en":"harvest","zh":"收割（庄稼）","pos":"","notes":"","frequency":0},
    {"en":"crop","zh":"庄稼,作物","pos":"","notes":"","frequency":0},
    {"en":"as","zh":"当……时,随着,因为","pos":"","notes":"","frequency":0},
    {"en":"temperature","zh":"温度","pos":"","notes":"","frequency":0},
    {"en":"sofa","zh":"长沙发","pos":"","notes":"","frequency":0},
    {"en":"snowman (pl. snowmen)","zh":"雪人","pos":"","notes":"","frequency":0},
    {"en":"blow","zh":"吹,刮,吹（气）","pos":"","notes":"","frequency":0},
    {"en":"shine","zh":"发光,照耀","pos":"","notes":"","frequency":0},
    {"en":"smell","zh":"有（或发出）……气味","pos":"","notes":"","frequency":0},
    {"en":"heat","zh":"热,热量","pos":"","notes":"","frequency":0},
    {"en":"sudden","zh":"突然的","pos":"","notes":"","frequency":0},
    {"en":"snowball","zh":"雪球","pos":"","notes":"","frequency":0},
    {"en":"fog","zh":"雾","pos":"","notes":"","frequency":0},
    {"en":"divide","zh":"（使）分开,分成","pos":"","notes":"","frequency":0},
    {"en":"divide ... into ...","zh":"把……分成……","pos":"","notes":"","frequency":0},
    {"en":"end","zh":"结束,终止","pos":"","notes":"","frequency":0},
    {"en":"beyond","zh":"超出,除……之外","pos":"","notes":"","frequency":0},
    {"en":"connect","zh":"把……联系起来,（使）连接","pos":"","notes":"","frequency":0},
    {"en":"be connected with","zh":"与……有联系","pos":"","notes":"","frequency":0},
    {"en":"positive","zh":"正面的,积极的,肯定的","pos":"","notes":"","frequency":0},
    {"en":"effect","zh":"影响,结果,效果","pos":"","notes":"","frequency":0},
    {"en":"average","zh":"平均的","pos":"","notes":"","frequency":0},
    {"en":"wet","zh":"湿的,潮的","pos":"","notes":"","frequency":0},
    {"en":"daylight","zh":"日光","pos":"","notes":"","frequency":0},
    {"en":"degree","zh":"度,度数","pos":"","notes":"","frequency":0},
    {"en":"on average","zh":"平均","pos":"","notes":"","frequency":0},
    {"en":"sunshine","zh":"阳光","pos":"","notes":"","frequency":0},
    {"en":"start","zh":"开头,开端","pos":"","notes":"","frequency":0},
    {"en":"snowstorm","zh":"雪暴,暴风雪","pos":"","notes":"","frequency":0},
    {"en":"awful","zh":"糟糕的,极讨厌的","pos":"","notes":"","frequency":0},
    {"en":"order","zh":"订购","pos":"","notes":"","frequency":0},
    {"en":"take care","zh":"保重","pos":"","notes":"","frequency":0},
    {"en":"frozen","zh":"结冰的,冷冻的","pos":"","notes":"","frequency":0},
    {"en":"thick","zh":"厚的,浓的","pos":"","notes":"","frequency":0},
    {"en":"deep","zh":"厚的,深的","pos":"","notes":"","frequency":0},
    {"en":"throw","zh":"扔","pos":"","notes":"","frequency":0},
    {"en":"sculpture","zh":"雕像,雕塑品译林英语八年级上册 Unit 1-6 单词表","pos":"","notes":"","frequency":0},
    {"en":"friendship","zh":"友谊","pos":"","notes":"","frequency":0},
    {"en":"honest","zh":"诚实的,正直的","pos":"","notes":"","frequency":0},
    {"en":"cheerful","zh":"快乐的,乐观的","pos":"","notes":"","frequency":0},
    {"en":"humorous","zh":"幽默的","pos":"","notes":"","frequency":0},
    {"en":"caring","zh":"关心他人的,体贴人的","pos":"","notes":"","frequency":0},
    {"en":"truth","zh":"事实","pos":"","notes":"","frequency":0},
    {"en":"joke","zh":"笑话,玩笑","pos":"","notes":"","frequency":0},
    {"en":"laugh","zh":"笑,发笑","pos":"","notes":"","frequency":0},
    {"en":"teenager","zh":"青少年","pos":"","notes":"","frequency":0},
    {"en":"unhappy","zh":"不开心的","pos":"","notes":"","frequency":0},
    {"en":"lie","zh":"撒谎","pos":"","notes":"","frequency":0},
    {"en":"person","zh":"人,个人","pos":"","notes":"","frequency":0},
    {"en":"thought","zh":"想法,主意","pos":"","notes":"","frequency":0},
    {"en":"ponytail","zh":"马尾辫","pos":"","notes":"","frequency":0},
    {"en":"seat","zh":"座位","pos":"","notes":"","frequency":0},
    {"en":"schoolwork","zh":"学校作业","pos":"","notes":"","frequency":0},
    {"en":"trustworthy","zh":"值得信赖的","pos":"","notes":"","frequency":0},
    {"en":"carefully","zh":"仔细地,小心地","pos":"","notes":"","frequency":0},
    {"en":"understand","zh":"理解","pos":"","notes":"","frequency":0},
    {"en":"bit","zh":"少量","pos":"","notes":"","frequency":0},
    {"en":"a little bit","zh":"有点儿","pos":"","notes":"","frequency":0},
    {"en":"funny","zh":"好笑的","pos":"","notes":"","frequency":0},
    {"en":"sense","zh":"理解力,感觉","pos":"","notes":"","frequency":0},
    {"en":"humour ( humor)","zh":"幽默","pos":"","notes":"","frequency":0},
    {"en":"sense of humour","zh":"幽默感","pos":"","notes":"","frequency":0},
    {"en":"bored","zh":"厌倦的,烦闷的","pos":"","notes":"","frequency":0},
    {"en":"energetic","zh":"精力充沛的","pos":"","notes":"","frequency":0},
    {"en":"active","zh":"活跃的,积极的","pos":"","notes":"","frequency":0},
    {"en":"encourage","zh":"鼓励","pos":"","notes":"","frequency":0},
    {"en":"believe","zh":"相信","pos":"","notes":"","frequency":0},
    {"en":"face","zh":"面临,面对","pos":"","notes":"","frequency":0},
    {"en":"secret","zh":"秘密","pos":"","notes":"","frequency":0},
    {"en":"keep secrets","zh":"保密","pos":"","notes":"","frequency":0},
    {"en":"worse","zh":"更差的","pos":"","notes":"","frequency":0},
    {"en":"worst","zh":"最差的","pos":"","notes":"","frequency":0},
    {"en":"height","zh":"身高,高度","pos":"","notes":"","frequency":0},
    {"en":"sec.","zh":"秒","pos":"","notes":"","frequency":0},
    {"en":"test","zh":"测验,考查,试验","pos":"","notes":"","frequency":0},
    {"en":"badminton","zh":"羽毛球运动","pos":"","notes":"","frequency":0},
    {"en":"however","zh":"然而","pos":"","notes":"","frequency":0},
    {"en":"balloon","zh":"气球","pos":"","notes":"","frequency":0},
    {"en":"scared","zh":"害怕,恐惧","pos":"","notes":"","frequency":0},
    {"en":"fight","zh":"搏斗,打斗,为……斗争","pos":"","notes":"","frequency":0},
    {"en":"dead","zh":"死的","pos":"","notes":"","frequency":0},
    {"en":"attack","zh":"攻击,袭击","pos":"","notes":"","frequency":0},
    {"en":"gone","zh":"离开了,不在","pos":"","notes":"","frequency":0},
    {"en":"danger","zh":"危险","pos":"","notes":"","frequency":0},
    {"en":"brave","zh":"勇敢的","pos":"","notes":"","frequency":0},
    {"en":"get along with some body","zh":"与某人和睦相处,关系良好","pos":"","notes":"","frequency":0},
    {"en":"listener","zh":"听者,听众","pos":"","notes":"","frequency":0},
    {"en":"nod","zh":"点头","pos":"","notes":"","frequency":0},
    {"en":"feeling","zh":"情感,感觉","pos":"","notes":"","frequency":0},
    {"en":"once","zh":"一……就,一旦","pos":"","notes":"","frequency":0},
    {"en":"patient","zh":"有耐心的","pos":"","notes":"","frequency":0},
    {"en":"thoughtful","zh":"体贴的,深思的","pos":"","notes":"","frequency":0},
    {"en":"secret","zh":"秘密的","pos":"","notes":"","frequency":0},
    {"en":"plastic","zh":"塑料的,塑料","pos":"","notes":"","frequency":0},
    {"en":"cheap","zh":"便宜的","pos":"","notes":"","frequency":0},
    {"en":"environment","zh":"环境","pos":"","notes":"","frequency":0},
    {"en":"few","zh":"不多,很少,很少人（或事物、地方）","pos":"","notes":"","frequency":0},
    {"en":"drama","zh":"戏剧,戏,剧","pos":"","notes":"","frequency":0},
    {"en":"foreign","zh":"外国的","pos":"","notes":"","frequency":0},
    {"en":"as","zh":"和……一样","pos":"","notes":"","frequency":0},
    {"en":"as ... as ...","zh":"和……一样……","pos":"","notes":"","frequency":0},
    {"en":"French","zh":"法语,法国人","pos":"","notes":"","frequency":0},
    {"en":"German","zh":"德语,德国人","pos":"","notes":"","frequency":0},
    {"en":"forward","zh":"向前","pos":"","notes":"","frequency":0},
    {"en":"look forward to","zh":"期待","pos":"","notes":"","frequency":0},
    {"en":"go","zh":"尝试","pos":"","notes":"","frequency":0},
    {"en":"have a go","zh":"尝试,试图","pos":"","notes":"","frequency":0},
    {"en":"earthquake","zh":"地震","pos":"","notes":"","frequency":0},
    {"en":"offer","zh":"提供","pos":"","notes":"","frequency":0},
    {"en":"programme ( program)","zh":"课程,计划,节目","pos":"","notes":"","frequency":0},
    {"en":"plenty","zh":"大量","pos":"","notes":"","frequency":0},
    {"en":"plenty of","zh":"大量","pos":"","notes":"","frequency":0},
    {"en":"hands-on","zh":"实际操作的","pos":"","notes":"","frequency":0},
    {"en":"attention","zh":"注意,专心,注意力","pos":"","notes":"","frequency":0},
    {"en":"pay attention to","zh":"注意","pos":"","notes":"","frequency":0},
    {"en":"aware","zh":"意识到,知道","pos":"","notes":"","frequency":0},
    {"en":"be aware of","zh":"意识到","pos":"","notes":"","frequency":0},
    {"en":"importance","zh":"重要性","pos":"","notes":"","frequency":0},
    {"en":"Japanese","zh":"日本（人）的,日语的","pos":"","notes":"","frequency":0},
    {"en":"ourselves","zh":"我们自己","pos":"","notes":"","frequency":0},
    {"en":"develop","zh":"形成,开发,（使）发展","pos":"","notes":"","frequency":0},
    {"en":"junior","zh":"初级的,青少年的","pos":"","notes":"","frequency":0},
    {"en":"rocket","zh":"火箭","pos":"","notes":"","frequency":0},
    {"en":"lunchtime","zh":"午餐时间","pos":"","notes":"","frequency":0},
    {"en":"least","zh":"最少的,最少","pos":"","notes":"","frequency":0},
    {"en":"international","zh":"国际（化）的","pos":"","notes":"","frequency":0},
    {"en":"vacation","zh":"（美）假期,度假","pos":"","notes":"","frequency":0},
    {"en":"textbook","zh":"课本,教材","pos":"","notes":"","frequency":0},
    {"en":"search","zh":"搜索,查找","pos":"","notes":"","frequency":0},
    {"en":"finish","zh":"完成,做好","pos":"","notes":"","frequency":0},
    {"en":"American","zh":"美国（人）的","pos":"","notes":"","frequency":0},
    {"en":"hamburger","zh":"汉堡包","pos":"","notes":"","frequency":0},
    {"en":"pizza","zh":"比萨饼","pos":"","notes":"","frequency":0},
    {"en":"fried","zh":"油炸的","pos":"","notes":"","frequency":0},
    {"en":"salad","zh":"沙拉","pos":"","notes":"","frequency":0},
    {"en":"chopstick","zh":"筷子","pos":"","notes":"","frequency":0},
    {"en":"movie","zh":"（美）电影","pos":"","notes":"","frequency":0},
    {"en":"difference","zh":"差异,不同（之处）","pos":"","notes":"","frequency":0},
    {"en":"cookie","zh":"（美）饼干","pos":"","notes":"","frequency":0},
    {"en":"fork","zh":"餐叉","pos":"","notes":"","frequency":0},
    {"en":"spoon","zh":"勺,匙","pos":"","notes":"","frequency":0},
    {"en":"boring","zh":"没趣的,令人厌倦的","pos":"","notes":"","frequency":0},
    {"en":"suggestion","zh":"建议","pos":"","notes":"","frequency":0},
    {"en":"uniform","zh":"校服,制服","pos":"","notes":"","frequency":0},
    {"en":"improve","zh":"改进,改善","pos":"","notes":"","frequency":0},
    {"en":"suggest","zh":"建议","pos":"","notes":"","frequency":0},
    {"en":"provide","zh":"提供","pos":"","notes":"","frequency":0},
    {"en":"moreover","zh":"此外","pos":"","notes":"","frequency":0},
    {"en":"yours sincerely","zh":"谨上,谨启","pos":"","notes":"","frequency":0},
    {"en":"learner","zh":"学习者","pos":"","notes":"","frequency":0},
    {"en":"feed","zh":"为……提供食物,喂养","pos":"","notes":"","frequency":0},
    {"en":"fish","zh":"钓鱼,捕鱼","pos":"","notes":"","frequency":0},
    {"en":"lifetime","zh":"一生,有生之年","pos":"","notes":"","frequency":0},
    {"en":"journey","zh":"旅程,旅行","pos":"","notes":"","frequency":0},
    {"en":"single","zh":"单个的,单身的","pos":"","notes":"","frequency":0},
    {"en":"against","zh":"逆,反对,紧靠","pos":"","notes":"","frequency":0},
    {"en":"fall behind","zh":"落后","pos":"","notes":"","frequency":0},
    {"en":"successful","zh":"有成效的,成功的","pos":"","notes":"","frequency":0},
    {"en":"drive","zh":"冲劲,本能需求","pos":"","notes":"","frequency":0},
    {"en":"guide","zh":"指导,给某人领路（或导游）","pos":"","notes":"","frequency":0},
    {"en":"lifelong","zh":"终身的","pos":"","notes":"","frequency":0},
    {"en":"inventor","zh":"发明家","pos":"","notes":"","frequency":0},
    {"en":"talent","zh":"天资,才能,有才能的人","pos":"","notes":"","frequency":0},
    {"en":"century","zh":"世纪,百年","pos":"","notes":"","frequency":0},
    {"en":"set ... apart","zh":"使……突出,使……与众不同","pos":"","notes":"","frequency":0},
    {"en":"print","zh":"印刷行业","pos":"","notes":"","frequency":0},
    {"en":"himself","zh":"他自己","pos":"","notes":"","frequency":0},
    {"en":"bookseller","zh":"书商","pos":"","notes":"","frequency":0},
    {"en":"in order to","zh":"为了","pos":"","notes":"","frequency":0},
    {"en":"return","zh":"归还","pos":"","notes":"","frequency":0},
    {"en":"curious","zh":"好奇的","pos":"","notes":"","frequency":0},
    {"en":"storm","zh":"暴风雨","pos":"","notes":"","frequency":0},
    {"en":"finding","zh":"调查发现","pos":"","notes":"","frequency":0},
    {"en":"predict","zh":"预测","pos":"","notes":"","frequency":0},
    {"en":"countless","zh":"数不尽的","pos":"","notes":"","frequency":0},
    {"en":"invention","zh":"发明","pos":"","notes":"","frequency":0},
    {"en":"come as no surprise","zh":"不足为奇","pos":"","notes":"","frequency":0},
    {"en":"invent","zh":"发明","pos":"","notes":"","frequency":0},
    {"en":"for free","zh":"免费","pos":"","notes":"","frequency":0},
    {"en":"greatness","zh":"伟大","pos":"","notes":"","frequency":0},
    {"en":"further","zh":"更远,较远","pos":"","notes":"","frequency":0},
    {"en":"success","zh":"成功","pos":"","notes":"","frequency":0},
    {"en":"Italian","zh":"意大利语,意大利人","pos":"","notes":"","frequency":0},
    {"en":"themselves","zh":"他们（她们,它们）自己","pos":"","notes":"","frequency":0},
    {"en":"conversation","zh":"交谈,谈话","pos":"","notes":"","frequency":0},
    {"en":"translate","zh":"翻译","pos":"","notes":"","frequency":0},
    {"en":"page","zh":"（书刊或纸张的）页","pos":"","notes":"","frequency":0},
    {"en":"badly","zh":"严重地,厉害地","pos":"","notes":"","frequency":0},
    {"en":"yourself","zh":"你自己","pos":"","notes":"","frequency":0},
    {"en":"yourselves","zh":"你们自己","pos":"","notes":"","frequency":0},
    {"en":"record","zh":"录制,记录","pos":"","notes":"","frequency":0},
    {"en":"printer","zh":"印刷工,印刷商,打印机","pos":"","notes":"","frequency":0},
    {"en":"dialect","zh":"方言","pos":"","notes":"","frequency":0},
    {"en":"besides","zh":"除……之外（还）","pos":"","notes":"","frequency":0},
    {"en":"possible","zh":"可能的","pos":"","notes":"","frequency":0},
    {"en":"as ... as possible","zh":"尽可能……","pos":"","notes":"","frequency":0},
    {"en":"sentence","zh":"句子","pos":"","notes":"","frequency":0},
    {"en":"rather than","zh":"而不是","pos":"","notes":"","frequency":0},
    {"en":"pronunciation","zh":"发音","pos":"","notes":"","frequency":0},
    {"en":"grammar","zh":"语法","pos":"","notes":"","frequency":0},
    {"en":"text","zh":"文本,文章","pos":"","notes":"","frequency":0},
    {"en":"slowly","zh":"慢速地,缓慢地","pos":"","notes":"","frequency":0},
    {"en":"whole","zh":"整个,全部","pos":"","notes":"","frequency":0},
    {"en":"speech","zh":"演讲,说话的能力","pos":"","notes":"","frequency":0},
    {"en":"aloud","zh":"出声地,大声地","pos":"","notes":"","frequency":0},
    {"en":"pronounce","zh":"发音","pos":"","notes":"","frequency":0},
    {"en":"correctly","zh":"正确地","pos":"","notes":"","frequency":0},
    {"en":"spelling","zh":"拼写","pos":"","notes":"","frequency":0},
    {"en":"nearby","zh":"在附近,附近的","pos":"","notes":"","frequency":0},
    {"en":"to one's surprise","zh":"令某人惊讶的是","pos":"","notes":"","frequency":0},
    {"en":"repeat","zh":"重复","pos":"","notes":"","frequency":0},
    {"en":"tourist","zh":"游客,观光者","pos":"","notes":"","frequency":0},
    {"en":"Moon cake","zh":"月饼","pos":"","notes":"","frequency":0},
    {"en":"shelf (pl. shelves)","zh":"架子","pos":"","notes":"","frequency":0},
    {"en":"rose","zh":"玫瑰（花）","pos":"","notes":"","frequency":0},
    {"en":"coloured paper","zh":"彩纸","pos":"","notes":"","frequency":0},
    {"en":"tape","zh":"胶带,用胶带粘贴","pos":"","notes":"","frequency":0},
    {"en":"glue","zh":"胶,胶水,（用胶水）黏合,粘贴","pos":"","notes":"","frequency":0},
    {"en":"fold","zh":"折叠","pos":"","notes":"","frequency":0},
    {"en":"complete","zh":"完成,结束,全部的","pos":"","notes":"","frequency":0},
    {"en":"DIY (= do-it-yourself)","zh":"自己动手","pos":"","notes":"","frequency":0},
    {"en":"crazy","zh":"狂热的,迷恋的","pos":"","notes":"","frequency":0},
    {"en":"be crazy about","zh":"热衷于","pos":"","notes":"","frequency":0},
    {"en":"born","zh":"天生的","pos":"","notes":"","frequency":0},
    {"en":"handyman (pl. handymen)","zh":"手巧的人","pos":"","notes":"","frequency":0},
    {"en":"mistake","zh":"错误","pos":"","notes":"","frequency":0},
    {"en":"power cut","zh":"断电,停电","pos":"","notes":"","frequency":0},
    {"en":"pipe","zh":"管道,管子","pos":"","notes":"","frequency":0},
    {"en":"fill ... with","zh":"使……充满","pos":"","notes":"","frequency":0},
    {"en":"unlucky","zh":"不幸的,不顺利的","pos":"","notes":"","frequency":0},
    {"en":"instead","zh":"反而","pos":"","notes":"","frequency":0},
    {"en":"course","zh":"课程","pos":"","notes":"","frequency":0},
    {"en":"mess","zh":"杂乱,不整洁","pos":"","notes":"","frequency":0},
    {"en":"in a mess","zh":"乱七八糟","pos":"","notes":"","frequency":0},
    {"en":"lamp","zh":"灯","pos":"","notes":"","frequency":0},
    {"en":"catch one's eye","zh":"引起某人注意","pos":"","notes":"","frequency":0},
    {"en":"surprised","zh":"惊奇的,感到意外的","pos":"","notes":"","frequency":0},
    {"en":"impossible","zh":"不可能的","pos":"","notes":"","frequency":0},
    {"en":"paint","zh":"油漆,绘画颜料","pos":"","notes":"","frequency":0},
    {"en":"can","zh":"金属容器,塑料容器","pos":"","notes":"","frequency":0},
    {"en":"everywhere","zh":"到处","pos":"","notes":"","frequency":0},
    {"en":"chalk","zh":"粉笔","pos":"","notes":"","frequency":0},
    {"en":"mark","zh":"标记,分数","pos":"","notes":"","frequency":0},
    {"en":"brush","zh":"刷子,画笔","pos":"","notes":"","frequency":0},
    {"en":"instructions","zh":"用法说明","pos":"","notes":"","frequency":0},
    {"en":"dangerous","zh":"危险的","pos":"","notes":"","frequency":0},
    {"en":"usual","zh":"通常的,寻常的","pos":"","notes":"","frequency":0},
    {"en":"tie-dye","zh":"扎染（织物）","pos":"","notes":"","frequency":0},
    {"en":"twist","zh":"使扭曲,使弯曲","pos":"","notes":"","frequency":0},
    {"en":"cloth","zh":"布料,织物","pos":"","notes":"","frequency":0},
    {"en":"tie","zh":"（用线,绳等）系,拴,绑,捆","pos":"","notes":"","frequency":0},
    {"en":"thread","zh":"线","pos":"","notes":"","frequency":0},
    {"en":"dye","zh":"给……染色,染,染料,染液","pos":"","notes":"","frequency":0},
    {"en":"untie","zh":"解开","pos":"","notes":"","frequency":0},
    {"en":"method","zh":"方法","pos":"","notes":"","frequency":0},
    {"en":"product","zh":"产品","pos":"","notes":"","frequency":0},
    {"en":"not only ... but also ...","zh":"不仅……而且……","pos":"","notes":"","frequency":0},
    {"en":"workshop","zh":"作坊","pos":"","notes":"","frequency":0},
    {"en":"dry","zh":"（使）变干,（把……）弄干","pos":"","notes":"","frequency":0},
    {"en":"pattern","zh":"图案,模式","pos":"","notes":"","frequency":0},
    {"en":"roll","zh":"卷,管","pos":"","notes":"","frequency":0},
    {"en":"reduce","zh":"减少","pos":"","notes":"","frequency":0},
    {"en":"waste","zh":"浪费,废料","pos":"","notes":"","frequency":0},
    {"en":"joy","zh":"高兴,乐趣","pos":"","notes":"","frequency":0},
    {"en":"glove","zh":"手套","pos":"","notes":"","frequency":0},
    {"en":"finger","zh":"（手套的）指部,手指","pos":"","notes":"","frequency":0},
    {"en":"button","zh":"纽扣,按钮","pos":"","notes":"","frequency":0},
    {"en":"onto","zh":"到……上,向……上","pos":"","notes":"","frequency":0},
    {"en":"wild","zh":"野生的,野生状态,自然环境","pos":"","notes":"","frequency":0},
    {"en":"dolphin","zh":"海豚","pos":"","notes":"","frequency":0},
    {"en":"eagle","zh":"雕","pos":"","notes":"","frequency":0},
    {"en":"fox","zh":"狐狸","pos":"","notes":"","frequency":0},
    {"en":"shark","zh":"鲨鱼","pos":"","notes":"","frequency":0},
    {"en":"wolf (pl. wolves)","zh":"狼","pos":"","notes":"","frequency":0},
    {"en":"zebra (pl. zebra, zebras)","zh":"斑马","pos":"","notes":"","frequency":0},
    {"en":"king","zh":"大王,国王","pos":"","notes":"","frequency":0},
    {"en":"tiny","zh":"极小的","pos":"","notes":"","frequency":0},
    {"en":"birth","zh":"出生","pos":"","notes":"","frequency":0},
    {"en":"round-the-clock","zh":"全天候的","pos":"","notes":"","frequency":0},
    {"en":"weigh","zh":"有……重","pos":"","notes":"","frequency":0},
    {"en":"satisfying","zh":"令人满意的","pos":"","notes":"","frequency":0},
    {"en":"giant panda","zh":"大熊猫","pos":"","notes":"","frequency":0},
    {"en":"in the wild","zh":"在野外","pos":"","notes":"","frequency":0},
    {"en":"serious","zh":"严重的","pos":"","notes":"","frequency":0},
    {"en":"even if","zh":"即使,尽管","pos":"","notes":"","frequency":0},
    {"en":"easily","zh":"很可能,容易地","pos":"","notes":"","frequency":0},
    {"en":"sick","zh":"生病的","pos":"","notes":"","frequency":0},
    {"en":"live on","zh":"以吃……为生","pos":"","notes":"","frequency":0},
    {"en":"mainly","zh":"主要地","pos":"","notes":"","frequency":0},
    {"en":"result","zh":"结果,后果","pos":"","notes":"","frequency":0},
    {"en":"as a result","zh":"因此","pos":"","notes":"","frequency":0},
    {"en":"government","zh":"政府","pos":"","notes":"","frequency":0},
    {"en":"action","zh":"行动","pos":"","notes":"","frequency":0},
    {"en":"take action","zh":"采取行动","pos":"","notes":"","frequency":0},
    {"en":"nature reserve","zh":"自然保护区","pos":"","notes":"","frequency":0},
    {"en":"thanks to","zh":"多亏,由于","pos":"","notes":"","frequency":0},
    {"en":"effort","zh":"努力","pos":"","notes":"","frequency":0},
    {"en":"increase","zh":"增加","pos":"","notes":"","frequency":0},
    {"en":"protection","zh":"保护","pos":"","notes":"","frequency":0},
    {"en":"growth","zh":"生长,发育,成长","pos":"","notes":"","frequency":0},
    {"en":"fat","zh":"胖的","pos":"","notes":"","frequency":0},
    {"en":"manage","zh":"完成（困难的事）","pos":"","notes":"","frequency":0},
    {"en":"whale","zh":"鲸","pos":"","notes":"","frequency":0},
    {"en":"hunt","zh":"猎杀","pos":"","notes":"","frequency":0},
    {"en":"meaningful","zh":"重要的","pos":"","notes":"","frequency":0},
    {"en":"in danger","zh":"处于危险中","pos":"","notes":"","frequency":0},
    {"en":"reason","zh":"理由,原因","pos":"","notes":"","frequency":0},
    {"en":"accept","zh":"收受,接受","pos":"","notes":"","frequency":0},
    {"en":"polar bear","zh":"北极熊","pos":"","notes":"","frequency":0},
    {"en":"meat eater","zh":"肉食动物（或人）","pos":"","notes":"","frequency":0},
    {"en":"melt","zh":"（使）融化","pos":"","notes":"","frequency":0},
    {"en":"drop","zh":"（使）降低,扔下,掉下","pos":"","notes":"","frequency":0},
    {"en":"blue whale","zh":"蓝鲸","pos":"","notes":"","frequency":0},
    {"en":"risk","zh":"危险,风险","pos":"","notes":"","frequency":0},
    {"en":"at risk","zh":"有危险","pos":"","notes":"","frequency":0},
    {"en":"Indian","zh":"印度（人）的","pos":"","notes":"","frequency":0},
    {"en":"rhino","zh":"犀牛","pos":"","notes":"","frequency":0},
    {"en":"horn","zh":"角","pos":"","notes":"","frequency":0},
    {"en":"disaster","zh":"灾害","pos":"","notes":"","frequency":0},
    {"en":"pollution","zh":"污染","pos":"","notes":"","frequency":0},
    {"en":"certain","zh":"某种,某些","pos":"","notes":"","frequency":0},
    {"en":"illness","zh":"疾病,病","pos":"","notes":"","frequency":0},
    {"en":"foggy","zh":"有雾的,雾茫茫的","pos":"","notes":"","frequency":0},
    {"en":"snowy","zh":"下雪多的,被雪覆盖的","pos":"","notes":"","frequency":0},
    {"en":"pleasant","zh":"令人愉快的","pos":"","notes":"","frequency":0},
    {"en":"yeah","zh":"是的","pos":"","notes":"","frequency":0},
    {"en":"hide","zh":"躲避,藏","pos":"","notes":"","frequency":0},
    {"en":"shower","zh":"阵雨","pos":"","notes":"","frequency":0},
    {"en":"memory","zh":"回忆","pos":"","notes":"","frequency":0},
    {"en":"stream","zh":"小河,溪","pos":"","notes":"","frequency":0},
    {"en":"shade","zh":"（树）荫","pos":"","notes":"","frequency":0},
    {"en":"lazy","zh":"慵懒的,懒惰的","pos":"","notes":"","frequency":0},
    {"en":"pool","zh":"水塘,池塘","pos":"","notes":"","frequency":0},
    {"en":"pile","zh":"堆","pos":"","notes":"","frequency":0},
    {"en":"upon","zh":"在……上","pos":"","notes":"","frequency":0},
    {"en":"harvest","zh":"收割（庄稼）","pos":"","notes":"","frequency":0},
    {"en":"crop","zh":"庄稼,作物","pos":"","notes":"","frequency":0},
    {"en":"as","zh":"当……时,随着,因为","pos":"","notes":"","frequency":0},
    {"en":"temperature","zh":"温度","pos":"","notes":"","frequency":0},
    {"en":"sofa","zh":"长沙发","pos":"","notes":"","frequency":0},
    {"en":"snowman (pl. snowmen)","zh":"雪人","pos":"","notes":"","frequency":0},
    {"en":"blow","zh":"吹,刮,吹（气）","pos":"","notes":"","frequency":0},
    {"en":"shine","zh":"发光,照耀","pos":"","notes":"","frequency":0},
    {"en":"smell","zh":"有（或发出）……气味","pos":"","notes":"","frequency":0},
    {"en":"heat","zh":"热,热量","pos":"","notes":"","frequency":0},
    {"en":"sudden","zh":"突然的","pos":"","notes":"","frequency":0},
    {"en":"snowball","zh":"雪球","pos":"","notes":"","frequency":0},
    {"en":"fog","zh":"雾","pos":"","notes":"","frequency":0},
    {"en":"divide","zh":"（使）分开,分成","pos":"","notes":"","frequency":0},
    {"en":"divide ... into ...","zh":"把……分成……","pos":"","notes":"","frequency":0},
    {"en":"end","zh":"结束,终止","pos":"","notes":"","frequency":0},
    {"en":"beyond","zh":"超出,除……之外","pos":"","notes":"","frequency":0},
    {"en":"connect","zh":"把……联系起来,（使）连接","pos":"","notes":"","frequency":0},
    {"en":"be connected with","zh":"与……有联系","pos":"","notes":"","frequency":0},
    {"en":"positive","zh":"正面的,积极的,肯定的","pos":"","notes":"","frequency":0},
    {"en":"effect","zh":"影响,结果,效果","pos":"","notes":"","frequency":0},
    {"en":"average","zh":"平均的","pos":"","notes":"","frequency":0},
    {"en":"wet","zh":"湿的,潮的","pos":"","notes":"","frequency":0},
    {"en":"daylight","zh":"日光","pos":"","notes":"","frequency":0},
    {"en":"degree","zh":"度,度数","pos":"","notes":"","frequency":0},
    {"en":"on average","zh":"平均","pos":"","notes":"","frequency":0},
    {"en":"sunshine","zh":"阳光","pos":"","notes":"","frequency":0},
    {"en":"start","zh":"开头,开端","pos":"","notes":"","frequency":0},
    {"en":"snowstorm","zh":"雪暴,暴风雪","pos":"","notes":"","frequency":0},
    {"en":"awful","zh":"糟糕的,极讨厌的","pos":"","notes":"","frequency":0},
    {"en":"order","zh":"订购","pos":"","notes":"","frequency":0},
    {"en":"take care","zh":"保重","pos":"","notes":"","frequency":0},
    {"en":"frozen","zh":"结冰的,冷冻的","pos":"","notes":"","frequency":0},
    {"en":"thick","zh":"厚的,浓的","pos":"","notes":"","frequency":0},
    {"en":"deep","zh":"厚的,深的","pos":"","notes":"","frequency":0},
    {"en":"throw","zh":"扔","pos":"","notes":"","frequency":0},
    {"en":"sculpture","zh":"雕像,雕塑品","pos":"","notes":"","frequency":0}
]};
